site_name: Pragmatic BIM Data Contract
site_url: https://schema.pragmaticbim.ch/
use_directory_urls: false

extra_css:
  - stylesheets/pragmatic-bim-brand.css

extra_javascript:
  - https://unpkg.com/mermaid@11/dist/mermaid.min.js
  - javascripts/mermaid-init.js
  - javascripts/classification-lang-switch.js

docs_dir: site/.md-src
site_dir: site/.html-build

theme:
  name: material
  palette:
    - scheme: default
      primary: custom
      accent: custom
  features:
    - search.suggest
    - search.highlight
    - content.code.copy
    - navigation.top

nav:
  - Pragmatic BIM Data Contract: index.md
  - Schema: schema/pragmatic-bim.docs.md
  - Mappings to IFC: mapping/index.md
  - Classifications: classification/index.md

plugins:
  - search
  - panzoom:
      full_screen: true

validation:
  unrecognized_links: ignore

markdown_extensions:
  - tables
  - toc:
      permalink: true
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - attr_list
  - md_in_html
