classDiagram
  direction TB
  Entity <|-- Agent
  Agent <|-- Company
  Agent <|-- Person
  Entity <|-- Message
  Entity <|-- PhysicalElement
  PhysicalElement <|-- Boundary
  PhysicalElement <|-- ConnectionPhysical
  PhysicalElement <|-- Equipment
  PhysicalElement <|-- Separator
  Entity <|-- VirtualEntity
  VirtualEntity <|-- AbstractCostRecord
  VirtualEntity <|-- AbstractTimeRecord
  VirtualEntity <|-- ConnectionVirtual
  VirtualEntity <|-- Material
  VirtualEntity <|-- Space
  VirtualEntity <|-- SpatialContext
  VirtualEntity <|-- System
  VirtualEntity <|-- TimeDependency
  PerformanceProperty <|-- AcousticProperty
  PerformanceProperty <|-- FireProperty
  PerformanceProperty <|-- MaterialProperty
  PerformanceProperty <|-- SecurityProperty
  PerformanceProperty <|-- StructuralProperty
  PerformanceProperty <|-- ThermalProperty
