#!/usr/bin/env python3
"""Merge split IFC mapping YAML sources into a single file with resolved anchors.

YAML anchors do not work across files. This script concatenates source parts in
dependency order so anchors defined in _conventions, _pset_fallbacks, and
_fragments resolve when entity files reference them.

This validates the merged *mapping specification* (repo YAML), not IFC model content.
An IFC file with only IfcSpace is fine — the adapter uses whichever entity blocks
apply to classes present in that file.

Usage:
    python scripts/merge_ifc_mapping.py
    python scripts/merge_ifc_mapping.py --check   # exit 1 if merged file is stale
"""

from __future__ import annotations

import argparse
import sys
from pathlib import Path

try:
    import yaml
except ImportError as exc:  # pragma: no cover
    raise SystemExit("PyYAML required: pip install pyyaml") from exc

REPO_ROOT = Path(__file__).resolve().parent.parent
MAPPINGS_DIR = REPO_ROOT / "contract" / "mappings"
ENTRYPOINT = MAPPINGS_DIR / "ifc_mapping.yaml"
OUTPUT = MAPPINGS_DIR / "ifc_mapping.merged.yaml"

HEADER_KEYS = {"mapping_version", "schema_uri", "canonical_type_version", "imports"}


def load_entrypoint() -> tuple[dict, list[str]]:
    data = yaml.safe_load(ENTRYPOINT.read_text(encoding="utf-8"))
    imports = data.get("imports")
    if not imports:
        raise ValueError(f"{ENTRYPOINT} must define imports:")
    header_lines = []
    for key in ("mapping_version", "schema_uri", "canonical_type_version"):
        if key in data:
            header_lines.append(f'{key}: "{data[key]}"' if key == "mapping_version" else f"{key}: {data[key]}")
    return data, imports


def read_part(import_path: str) -> str:
    path = MAPPINGS_DIR / import_path
    if not path.is_file():
        raise FileNotFoundError(f"Missing import: {path}")
    body = path.read_text(encoding="utf-8")
    # Drop leading comment lines for cleaner merge (keep one blank line between parts).
    while body.startswith("#"):
        _, _, body = body.partition("\n")
    return body.strip() + "\n"


def build_merged_text(imports: list[str]) -> str:
    entry = yaml.safe_load(ENTRYPOINT.read_text(encoding="utf-8"))
    parts: list[str] = [
        "# AUTO-GENERATED by scripts/merge_ifc_mapping.py — do not edit by hand.",
        "# Edit split sources listed in ifc_mapping.yaml imports, then re-run the merge script.",
        "",
        f'mapping_version: "{entry["mapping_version"]}"',
        f'schema_uri: {entry["schema_uri"]}',
        f'canonical_type_version: "{entry["canonical_type_version"]}"',
        "",
    ]

    entity_chunks: list[str] = []
    for import_path in imports:
        if import_path.startswith("entities/"):
            entity_chunks.append(read_part(import_path))
            continue
        parts.append(read_part(import_path))
        parts.append("")

    if entity_chunks:
        parts.append("entities:\n")
        for chunk in entity_chunks:
            parts.append(chunk)
            parts.append("")
        parts.append("")

    return "\n".join(parts).rstrip() + "\n"


REQUIRED_SECTIONS = ("conventions", "relationships", "entities")
# Spot-check that merge did not drop core mapping blocks (not an IFC file requirement).
REQUIRED_ENTITY_MAPPINGS = ("IfcSpace", "IfcBuildingStorey", "IfcWall")


def validate_merged(text: str) -> dict:
    """Validate merged mapping YAML structure after concat merge."""
    data = yaml.safe_load(text)
    for section in REQUIRED_SECTIONS:
        if section not in data:
            raise ValueError(f"Merged mapping missing required section: {section}")
    entities = data["entities"]
    if not entities:
        raise ValueError("Merged mapping has empty entities section")
    missing = [name for name in REQUIRED_ENTITY_MAPPINGS if name not in entities]
    if missing:
        raise ValueError(f"Merged mapping missing expected entity blocks: {', '.join(missing)}")
    for name, block in entities.items():
        if not isinstance(block, dict):
            raise ValueError(f"entities.{name} is not a mapping")
        if "content_kind" not in block:
            raise ValueError(f"entities.{name} missing content_kind")
        has_type = any(k in block for k in ("canonical_type", "canonical_type_from", "inherits"))
        if not has_type:
            raise ValueError(f"entities.{name} missing canonical_type, canonical_type_from, or inherits")
    return data


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--check",
        action="store_true",
        help="Verify ifc_mapping.merged.yaml matches current sources (CI mode)",
    )
    args = parser.parse_args()

    _, imports = load_entrypoint()
    merged_text = build_merged_text(imports)
    validate_merged(merged_text)

    if args.check:
        if not OUTPUT.is_file():
            print(f"Missing {OUTPUT.relative_to(REPO_ROOT)} — run merge script", file=sys.stderr)
            return 1
        if OUTPUT.read_text(encoding="utf-8") != merged_text:
            print(f"Stale {OUTPUT.relative_to(REPO_ROOT)} — run: python scripts/merge_ifc_mapping.py", file=sys.stderr)
            return 1
        print("ifc_mapping.merged.yaml is up to date")
        return 0

    OUTPUT.write_text(merged_text, encoding="utf-8")
    entity_count = len(yaml.safe_load(merged_text)["entities"])
    print(f"Wrote {OUTPUT.relative_to(REPO_ROOT)} ({entity_count} entities)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
