"""Source data for abstract building space name classification."""

from __future__ import annotations

from dataclasses import dataclass, field

RN_NS = "https://example.org/abstract/building-space-name-classification/"
ABS_NS = "https://example.org/abstract/building-space-activity-classification/"


@dataclass(frozen=True)
class RoomNameCategory:
    local_name: str
    notation: str
    label_en: str
    label_de: str
    definition_en: str
    definition_de: str


@dataclass(frozen=True)
class RoomNameGroup:
    local_name: str
    notation: str
    category: str
    label_en: str
    label_de: str
    definition_en: str
    definition_de: str


@dataclass(frozen=True)
class RoomNameConcept:
    local_name: str
    notation: str
    label_en: str
    label_de: str
    definition_en: str
    definition_de: str
    category: str
    group: str
    activity_codes: list[str] = field(default_factory=list)
    alt_labels_en: list[str] = field(default_factory=list)
    alt_labels_de: list[str] = field(default_factory=list)


CATEGORIES: list[RoomNameCategory] = [
    RoomNameCategory("RN_RES", "RN-01", "Residential", "Wohnen",
                     "Normalized room names for residential living spaces.",
                     "Normalisierte Raumbezeichnungen fuer Wohnnutzungen."),
    RoomNameCategory("RN_WRK", "RN-02", "Work", "Arbeit",
                     "Normalized room names for office and knowledge work.",
                     "Normalisierte Raumbezeichnungen fuer Buero- und Wissensarbeit."),
    RoomNameCategory("RN_CIR", "RN-03", "Circulation", "Erschliessung",
                     "Normalized room names for circulation and access spaces.",
                     "Normalisierte Raumbezeichnungen fuer Erschliessungsraeume."),
    RoomNameCategory("RN_HYG", "RN-04", "Hygiene", "Hygiene",
                     "Normalized room names for sanitary and changing spaces.",
                     "Normalisierte Raumbezeichnungen fuer Hygiene- und Sanitaerraeume."),
    RoomNameCategory("RN_HLC", "RN-05", "Healthcare", "Gesundheit",
                     "Normalized room names for medical and care spaces.",
                     "Normalisierte Raumbezeichnungen fuer medizinische und pflegerische Raeume."),
    RoomNameCategory("RN_LRN", "RN-06", "Education", "Bildung",
                     "Normalized room names for teaching and learning spaces.",
                     "Normalisierte Raumbezeichnungen fuer Bildungs- und Lernraeume."),
    RoomNameCategory("RN_COM", "RN-07", "Commercial", "Gewerbe",
                     "Normalized room names for hospitality and retail spaces.",
                     "Normalisierte Raumbezeichnungen fuer Gastronomie- und Verkaufsraeume."),
    RoomNameCategory("RN_IND", "RN-08", "Industrial", "Industrie",
                     "Normalized room names for production and workshop spaces.",
                     "Normalisierte Raumbezeichnungen fuer Produktions- und Werkraeume."),
    RoomNameCategory("RN_TEC", "RN-09", "Technical", "Technik",
                     "Normalized room names for building services and plant rooms.",
                     "Normalisierte Raumbezeichnungen fuer Technik- und Anlagenraeume."),
    RoomNameCategory("RN_STO", "RN-10", "Storage", "Lager",
                     "Normalized room names for storage and ancillary spaces.",
                     "Normalisierte Raumbezeichnungen fuer Lager- und Nebenraeume."),
    RoomNameCategory("RN_OUT", "RN-11", "Outdoor", "Aussen",
                     "Normalized room names for exterior spaces modeled as IfcSpace.",
                     "Normalisierte Raumbezeichnungen fuer als IfcSpace modellierte Aussenraeume."),
    RoomNameCategory("RN_VOI", "RN-12", "Void", "Hohlraum",
                     "Normalized room names for non-occupiable void and special spaces.",
                     "Normalisierte Raumbezeichnungen fuer nicht nutzbare Hohl- und Sonderraeume."),
]

GROUPS: list[RoomNameGroup] = [
    # Residential
    RoomNameGroup("RN_RES_LIV_GRP", "RN-01-10", "RN_RES", "Living and sleeping", "Wohnen und Schlafen",
                  "Rooms for daily living, sleeping, and dining.", "Raeume fuer Wohnen, Schlafen und Essen."),
    RoomNameGroup("RN_RES_SVC_GRP", "RN-01-20", "RN_RES", "Residential services", "Wohnliche Dienste",
                  "Kitchen, bathroom, laundry, and utility spaces within dwellings.",
                  "Kueche, Bad, Waesche und Hauswirtschaft in Wohneinheiten."),
    RoomNameGroup("RN_RES_UNT_GRP", "RN-01-30", "RN_RES", "Dwelling unit level", "Wohneinheitsebene",
                  "Entry, storage, and whole-unit spaces.", "Eingang, Abstell- und Gesamtwohnflaechen."),
    # Work
    RoomNameGroup("RN_WRK_IND_GRP", "RN-02-10", "RN_WRK", "Individual work", "Einzelarbeit",
                  "Enclosed and focus workspaces.", "Geschlossene und Fokus-Arbeitsplaetze."),
    RoomNameGroup("RN_WRK_COL_GRP", "RN-02-20", "RN_WRK", "Collaboration", "Zusammenarbeit",
                  "Meeting and informal collaboration spaces.", "Besprechungs- und informelle Teamraeume."),
    RoomNameGroup("RN_WRK_ADM_GRP", "RN-02-30", "RN_WRK", "Reception and administration", "Empfang und Verwaltung",
                  "Reception, management, and open administrative areas.",
                  "Empfang, Fuehrung und offene Verwaltungsflaechen."),
    # Circulation
    RoomNameGroup("RN_CIR_HOR_GRP", "RN-03-10", "RN_CIR", "Horizontal circulation", "Horizontale Erschliessung",
                  "Corridors, lobbies, and horizontal access routes.",
                  "Flure, Hallen und horizontale Zugaenge."),
    RoomNameGroup("RN_CIR_VRT_GRP", "RN-03-20", "RN_CIR", "Vertical circulation", "Vertikale Erschliessung",
                  "Stairs, ramps, lifts, and landings.", "Treppen, Rampen, Aufzuege und Podeste."),
    RoomNameGroup("RN_CIR_INT_GRP", "RN-03-30", "RN_CIR", "Activity-integral circulation", "Hauptnutzungserschliessung",
                  "Circulation spaces integral to the main building activity.",
                  "Erschliessung als Teil der Hauptnutzung."),
    # Hygiene
    RoomNameGroup("RN_HYG_WC_GRP", "RN-04-10", "RN_HYG", "Toilets", "Toiletten",
                  "Toilet rooms by accessibility and gender provision.",
                  "WC-Raeume nach Barrierefreiheit und Geschlechterausstattung."),
    RoomNameGroup("RN_HYG_WSH_GRP", "RN-04-20", "RN_HYG", "Wash and change", "Waschen und Umziehen",
                  "Shower, changing, and locker spaces.", "Duschen, Umziehen und Schliessfaecher."),
    RoomNameGroup("RN_HYG_CLK_GRP", "RN-04-30", "RN_HYG", "Coat check", "Mantelablage",
                  "Coat check and entry cloakroom spaces.", "Garderobe und Mantelablage am Eingang."),
    # Healthcare
    RoomNameGroup("RN_HLC_INP_GRP", "RN-05-10", "RN_HLC", "Inpatient care", "Stationaere Pflege",
                  "Rooms for inpatient stay and recovery.", "Raeume fuer stationaeren Aufenthalt und Erholung."),
    RoomNameGroup("RN_HLC_CLN_GRP", "RN-05-20", "RN_HLC", "Clinical treatment", "Klinische Behandlung",
                  "Treatment, surgery, and procedure spaces.", "Behandlungs-, Operations- und Eingriffsraeume."),
    RoomNameGroup("RN_HLC_SUP_GRP", "RN-05-30", "RN_HLC", "Diagnostics and support", "Diagnostik und Support",
                  "Imaging, laboratory, waiting, and nursing support spaces.",
                  "Bildgebung, Labor, Warten und Pflegestation."),
    # Education
    RoomNameGroup("RN_LRN_INS_GRP", "RN-06-10", "RN_LRN", "Instruction", "Unterricht",
                  "Classrooms, lecture halls, and seminar spaces.", "Klassenzimmer, Hoersaele und Seminarraeume."),
    RoomNameGroup("RN_LRN_STY_GRP", "RN-06-20", "RN_LRN", "Self-directed learning", "Selbstgesteuertes Lernen",
                  "Library, study, and training workshop spaces.", "Bibliothek, Lernraeume und Ausbildungswerkstaetten."),
    RoomNameGroup("RN_LRN_ASM_GRP", "RN-06-30", "RN_LRN", "Assembly and special subjects", "Versammlung und Fachraeume",
                  "Auditoria, art studios, and science laboratories.", "Aula, Ateliers und naturwissenschaftliche Laboratorien."),
    # Commercial
    RoomNameGroup("RN_COM_DIN_GRP", "RN-07-10", "RN_COM", "Dining and beverage", "Gastronomie",
                  "Cafeterias, restaurants, bars, and food courts.", "Cafeterias, Restaurants, Bars und Food-Courts."),
    RoomNameGroup("RN_COM_RET_GRP", "RN-07-20", "RN_COM", "Retail and exhibition", "Verkauf und Ausstellung",
                  "Retail, sales, kiosk, and exhibition spaces.", "Verkaufs-, Ausstellungs- und Kioskbereiche."),
    RoomNameGroup("RN_COM_HSP_GRP", "RN-07-30", "RN_COM", "Hospitality", "Beherbergung",
                  "Hotel and guest accommodation rooms.", "Hotel- und Gaestezimmer."),
    # Industrial
    RoomNameGroup("RN_IND_PRD_GRP", "RN-08-10", "RN_IND", "Production", "Produktion",
                  "Workshops, production halls, assembly, and clean rooms.",
                  "Werkstaetten, Produktionshallen, Montage und Reinraeume."),
    RoomNameGroup("RN_IND_LOG_GRP", "RN-08-20", "RN_IND", "Logistics", "Logistik",
                  "Warehousing, loading, quality control, and maintenance.",
                  "Lagerung, Be-/Entladung, Qualitaetskontrolle und Wartung."),
    RoomNameGroup("RN_IND_SPC_GRP", "RN-08-30", "RN_IND", "Special industrial", "Spezielle Industrie",
                  "Covered yards and special industrial spaces.", "Ueberdeckte Hoefe und spezielle Industrieraeume."),
    # Technical
    RoomNameGroup("RN_TEC_MEP_GRP", "RN-09-10", "RN_TEC", "HVAC and plumbing plant", "HLK und Sanitaertechnik",
                  "Heating, cooling, pumping, and fire suppression plant rooms.",
                  "Heizungs-, Kaelte-, Pumpen- und Sprinklerzentralen."),
    RoomNameGroup("RN_TEC_ELC_GRP", "RN-09-20", "RN_TEC", "Electrical and IT plant", "Elektro- und IT-Technik",
                  "Electrical, generator, transformer, server, and telecom rooms.",
                  "Elektro-, Generator-, Transformator-, Server- und Kommunikationsraeume."),
    RoomNameGroup("RN_TEC_UTL_GRP", "RN-09-30", "RN_TEC", "Metering and waste", "Zaehler und Entsorgung",
                  "Meter rooms and waste handling spaces.", "Zaehlerraeume und Abfallraeume."),
    # Storage
    RoomNameGroup("RN_STO_GEN_GRP", "RN-10-10", "RN_STO", "General storage types", "Allgemeine Lagertypen",
                  "General, supply, equipment, and janitor storage.", "Allgemeine, Material-, Geraete- und Hauswartlager."),
    RoomNameGroup("RN_STO_SPC_GRP", "RN-10-20", "RN_STO", "Specialized storage", "Speziallager",
                  "Archives, mail rooms, and cold storage.", "Archive, Postraeume und Kuehllager."),
    # Outdoor
    RoomNameGroup("RN_OUT_PLT_GRP", "RN-11-10", "RN_OUT", "Exterior platforms", "Aussenplattformen",
                  "Balconies, terraces, and patios.", "Balkone, Terrassen und Innenhoefe."),
    RoomNameGroup("RN_OUT_LND_GRP", "RN-11-20", "RN_OUT", "Landscape and recreation", "Landschaft und Freizeit",
                  "Gardens, playgrounds, and pool areas.", "Gaerten, Spielplaetze und Beckenflaechen."),
    RoomNameGroup("RN_OUT_COV_GRP", "RN-11-30", "RN_OUT", "Covered exterior routes", "Ueberdachte Aussenwege",
                  "Covered walkways and porticos.", "Ueberdachte Fusswege und Portiken."),
    # Void
    RoomNameGroup("RN_VOI_VRT_GRP", "RN-12-10", "RN_VOI", "Vertical voids", "Vertikale Hohlraeume",
                  "Shafts and service risers.", "Schaechte und Steigzonen."),
    RoomNameGroup("RN_VOI_PLN_GRP", "RN-12-20", "RN_VOI", "Plenums and air volumes", "Installations- und Luftraeume",
                  "Plenums, mechanical voids, and modeled air spaces.", "Installationshohlraeume und modellierter Luftraum."),
    RoomNameGroup("RN_VOI_STR_GRP", "RN-12-30", "RN_VOI", "Structural and special voids", "Konstruktions- und Sonderraeume",
                  "Atria, structural voids, and interior parking stalls.", "Atrien, Konstruktionshohlraeume und Innenparkierung."),
]

CONCEPTS: list[RoomNameConcept] = [
    # Residential — living and sleeping (RN-01-10)
    RoomNameConcept("RN_RES_BED", "RN-01-10-01", "Bedroom", "Schlafzimmer",
                    "Room primarily used for sleeping.", "Raum primaer fuer Schlafen.",
                    "RN_RES", "RN_RES_LIV_GRP", ["M-RES"]),
    RoomNameConcept("RN_RES_LIV", "RN-01-10-02", "Living Room", "Wohnzimmer",
                    "Room for daily living and relaxation.", "Raum fuer Wohnen und Entspannung.",
                    "RN_RES", "RN_RES_LIV_GRP", ["M-RES"]),
    RoomNameConcept("RN_RES_DIN", "RN-01-10-03", "Dining Room", "Esszimmer",
                    "Room for eating meals.", "Raum fuer Mahlzeiten.",
                    "RN_RES", "RN_RES_LIV_GRP", ["M-RES"]),
    RoomNameConcept("RN_RES_STU", "RN-01-10-04", "Home Study", "Arbeitszimmer",
                    "Residential room for study or home office work.", "Wohnlicher Raum fuer Arbeit oder Studium.",
                    "RN_RES", "RN_RES_LIV_GRP", ["M-RES"]),
    RoomNameConcept("RN_RES_GST", "RN-01-10-05", "Guest Room", "Gaestezimmer",
                    "Room for overnight guests.", "Raum fuer ueber Nacht bleibende Gaeste.",
                    "RN_RES", "RN_RES_LIV_GRP", ["M-RES"]),
    # Residential — services (RN-01-20)
    RoomNameConcept("RN_RES_KIT", "RN-01-20-01", "Kitchen", "Kueche",
                    "Room for food preparation.", "Raum fuer Speisezubereitung.",
                    "RN_RES", "RN_RES_SVC_GRP", ["M-RES"]),
    RoomNameConcept("RN_RES_BTH", "RN-01-20-02", "Bathroom", "Badezimmer",
                    "Room with bath, shower, or personal hygiene fixtures.", "Raum mit Bad, Dusche oder Koerperpflege.",
                    "RN_RES", "RN_RES_SVC_GRP", ["M-RES"]),
    RoomNameConcept("RN_RES_LAU", "RN-01-20-03", "Laundry Room", "Waschkueche",
                    "Room for washing and drying clothes.", "Raum fuer Waeschepflege.",
                    "RN_RES", "RN_RES_SVC_GRP", ["M-RES"]),
    RoomNameConcept("RN_RES_UTL", "RN-01-20-04", "Utility Room", "Hauswirtschaftsraum",
                    "Room for domestic utilities and equipment.", "Raum fuer haushaltstechnische Einrichtungen.",
                    "RN_RES", "RN_RES_SVC_GRP", ["M-RES"]),
    # Residential — unit level (RN-01-30)
    RoomNameConcept("RN_RES_ENT", "RN-01-30-01", "Residential Entry", "Wohnungseingang",
                    "Entry space within a dwelling unit.", "Eingangsbereich innerhalb einer Wohneinheit.",
                    "RN_RES", "RN_RES_UNT_GRP", ["M-RES"]),
    RoomNameConcept("RN_RES_CLO", "RN-01-30-02", "Residential Closet", "Abstellraum Wohnen",
                    "Small storage within a dwelling unit.", "Kleiner Abstellraum innerhalb einer Wohneinheit.",
                    "RN_RES", "RN_RES_UNT_GRP", ["M-RES"]),
    RoomNameConcept("RN_RES_APT", "RN-01-30-03", "Apartment Unit", "Wohneinheit",
                    "Generic residential unit space when not subdivided further.", "Generische Wohneinheit ohne weitere Unterteilung.",
                    "RN_RES", "RN_RES_UNT_GRP", ["M-RES"]),
    # Work — individual (RN-02-10)
    RoomNameConcept("RN_WRK_OFF", "RN-02-10-01", "Office", "Buero",
                    "Enclosed office for individual or shared desk work.", "Buero fuer Einzel- oder Gruppenarbeit.",
                    "RN_WRK", "RN_WRK_IND_GRP", ["M-WRK-KNW"]),
    RoomNameConcept("RN_WRK_OPN", "RN-02-10-02", "Open-Plan Office", "Grossraumbuero",
                    "Open office landscape without full-height partitions.", "Offene Burolandschaft ohne geschlossene Zellbueros.",
                    "RN_WRK", "RN_WRK_IND_GRP", ["M-WRK-KNW"]),
    RoomNameConcept("RN_WRK_FCS", "RN-02-10-03", "Focus Room", "Fokusraum",
                    "Small room for concentrated individual work.", "Kleiner Raum fuer konzentrierte Einzelarbeit.",
                    "RN_WRK", "RN_WRK_IND_GRP", ["M-WRK-KNW"]),
    RoomNameConcept("RN_WRK_PHN", "RN-02-10-04", "Phone Booth", "Telefonbox",
                    "Small enclosure for private calls.", "Kleine Kabine fuer Telefongespraeche.",
                    "RN_WRK", "RN_WRK_IND_GRP", ["M-WRK-KNW"]),
    RoomNameConcept("RN_WRK_COW", "RN-02-10-05", "Coworking Space", "Coworking-Flaeche",
                    "Shared flexible workspace.", "Gemeinschaftlich genutzter flexibler Arbeitsraum.",
                    "RN_WRK", "RN_WRK_IND_GRP", ["M-WRK-KNW"]),
    # Work — collaboration (RN-02-20)
    RoomNameConcept("RN_WRK_MTG", "RN-02-20-01", "Meeting Room", "Besprechungsraum",
                    "Room for small group meetings.", "Raum fuer kleine Besprechungen.",
                    "RN_WRK", "RN_WRK_COL_GRP", ["M-WRK-KNW"]),
    RoomNameConcept("RN_WRK_CNF", "RN-02-20-02", "Conference Room", "Konferenzraum",
                    "Room for formal meetings and presentations.", "Raum fuer formelle Sitzungen und Praesentationen.",
                    "RN_WRK", "RN_WRK_COL_GRP", ["M-WRK-KNW"]),
    RoomNameConcept("RN_WRK_BRK", "RN-02-20-03", "Break Room", "Pausenraum",
                    "Informal staff rest and refreshment space.", "Informeller Raum fuer Pausen.",
                    "RN_WRK", "RN_WRK_COL_GRP", ["M-WRK-KNW"]),
    # Work — reception/admin (RN-02-30)
    RoomNameConcept("RN_WRK_REC", "RN-02-30-01", "Reception", "Empfang",
                    "Visitor reception and waiting area.", "Empfang und Wartebereich fuer Besucher.",
                    "RN_WRK", "RN_WRK_ADM_GRP", ["M-WRK-KNW"]),
    RoomNameConcept("RN_WRK_ADM", "RN-02-30-02", "Administrative Office", "Verwaltungsbuero",
                    "Office for administrative staff.", "Buero fuer Verwaltungspersonal.",
                    "RN_WRK", "RN_WRK_ADM_GRP", ["M-WRK-KNW"]),
    RoomNameConcept("RN_WRK_MNG", "RN-02-30-03", "Manager Office", "Fuehrungsbuero",
                    "Office for management roles.", "Buero fuer Fuehrungsfunktionen.",
                    "RN_WRK", "RN_WRK_ADM_GRP", ["M-WRK-KNW"]),
    RoomNameConcept("RN_WRK_OAD", "RN-02-30-04", "Open Administrative Area", "Offene Verwaltungsflaeche",
                    "Open administrative work area.", "Offene Verwaltungsarbeitsflaeche.",
                    "RN_WRK", "RN_WRK_ADM_GRP", ["M-WRK-KNW"]),
    # Circulation — horizontal (RN-03-10); AIS merged into COR
    RoomNameConcept(
        "RN_CIR_COR", "RN-03-10-01", "Corridor", "Flur",
        "Horizontal circulation passage, including narrow aisles between rows or functions.",
        "Horizontaler Verbindungsflur, einschliesslich schmaler Durchgaenge zwischen Reihen oder Funktionen.",
        "RN_CIR", "RN_CIR_HOR_GRP", ["S-CIR-HOR"],
        alt_labels_en=["Aisle"], alt_labels_de=["Korridor", "Seitengang"],
    ),
    RoomNameConcept("RN_CIR_LOB", "RN-03-10-02", "Lobby", "Eingangshalle",
                    "Main entrance lobby or reception hall.", "Eingangshalle oder Empfoyer.",
                    "RN_CIR", "RN_CIR_HOR_GRP", ["S-CIR-HOR", "M-CIR"]),
    RoomNameConcept("RN_CIR_ENT", "RN-03-10-03", "Entrance Hall", "Entree",
                    "Building entrance transition space.", "Uebergangsraum am Gebaeudeeingang.",
                    "RN_CIR", "RN_CIR_HOR_GRP", ["S-CIR-HOR"]),
    RoomNameConcept("RN_CIR_VES", "RN-03-10-04", "Vestibule", "Vorraum",
                    "Transition space between exterior and interior.", "Uebergangsraum zwischen Aussen und Innen.",
                    "RN_CIR", "RN_CIR_HOR_GRP", ["S-CIR-HOR"]),
    # Circulation — vertical (RN-03-20)
    RoomNameConcept("RN_CIR_STR", "RN-03-20-01", "Stairwell", "Treppenhaus",
                    "Enclosed stair and landing volume.", "Treppenhaus mit Podesten.",
                    "RN_CIR", "RN_CIR_VRT_GRP", ["S-CIR-VRT-MAN"]),
    RoomNameConcept("RN_CIR_ELV", "RN-03-20-02", "Elevator Lobby", "Aufzugszone",
                    "Waiting area at elevator stops.", "Wartebereich an Aufzugshaltestellen.",
                    "RN_CIR", "RN_CIR_VRT_GRP", ["S-CIR-VRT-MEC"]),
    RoomNameConcept("RN_CIR_RAM", "RN-03-20-03", "Ramp", "Rampe",
                    "Inclined accessible circulation route.", "Geneigte barrierefreie Erschliessung.",
                    "RN_CIR", "RN_CIR_VRT_GRP", ["S-CIR-VRT-MAN"]),
    RoomNameConcept("RN_CIR_LND", "RN-03-20-04", "Landing", "Podest",
                    "Stair or ramp landing platform.", "Treppen- oder Rampenpodest.",
                    "RN_CIR", "RN_CIR_VRT_GRP", ["S-CIR-VRT-MAN"]),
    # Circulation — integral (RN-03-30)
    RoomNameConcept("RN_CIR_GAL", "RN-03-30-01", "Gallery", "Galerie",
                    "Circulation gallery integral to main activity.", "Erschliessungsgalerie als Teil der Hauptnutzung.",
                    "RN_CIR", "RN_CIR_INT_GRP", ["M-CIR"]),
    # Hygiene — toilets (RN-04-10)
    RoomNameConcept("RN_HYG_WC_M", "RN-04-10-01", "Male Toilet", "Herren-WC",
                    "Toilet room for male use.", "WC fuer Maenner.",
                    "RN_HYG", "RN_HYG_WC_GRP", ["S-HYG-WC-M"]),
    RoomNameConcept("RN_HYG_WC_F", "RN-04-10-02", "Female Toilet", "Damen-WC",
                    "Toilet room for female use.", "WC fuer Frauen.",
                    "RN_HYG", "RN_HYG_WC_GRP", ["S-HYG-WC-F"]),
    RoomNameConcept("RN_HYG_WC_IV", "RN-04-10-03", "Accessible Toilet", "Barrierefreies WC",
                    "Wheelchair-accessible toilet room.", "Rollstuhlgaengiges WC.",
                    "RN_HYG", "RN_HYG_WC_GRP", ["S-HYG-WC-IV"]),
    RoomNameConcept("RN_HYG_WC_MIX", "RN-04-10-04", "Unisex Toilet", "Allgemeines WC",
                    "Toilet room for mixed or all-gender use.", "WC fuer gemischte oder all-gender Nutzung.",
                    "RN_HYG", "RN_HYG_WC_GRP", ["S-HYG-WC-MIX"]),
    # Hygiene — wash/change (RN-04-20)
    RoomNameConcept("RN_HYG_SHW", "RN-04-20-01", "Shower Room", "Duschraum",
                    "Room with shower facilities.", "Raum mit Duscheinrichtungen.",
                    "RN_HYG", "RN_HYG_WSH_GRP", ["S-HYG-SHW"]),
    RoomNameConcept("RN_HYG_CHG", "RN-04-20-02", "Changing Room", "Umkleideraum",
                    "Room for changing clothes.", "Raum zum Umziehen.",
                    "RN_HYG", "RN_HYG_WSH_GRP", ["S-HYG-SHW"]),
    RoomNameConcept("RN_HYG_LCK", "RN-04-20-03", "Locker Room", "Schliessfachraum",
                    "Room with personal lockers.", "Raum mit persoenlichen Schliessfaechern.",
                    "RN_HYG", "RN_HYG_WSH_GRP", ["S-STO-LCK"]),
    # Hygiene — cloakroom (RN-04-30)
    RoomNameConcept("RN_HYG_GRD", "RN-04-30-01", "Cloakroom", "Garderobe",
                    "Staffed or unstaffed coat check at entry.", "Garderobe mit oder ohne Bedienung am Eingang.",
                    "RN_HYG", "RN_HYG_CLK_GRP", ["S-HYG-GRD"]),
    # Healthcare — inpatient (RN-05-10)
    RoomNameConcept("RN_HLC_PAT", "RN-05-10-01", "Patient Room", "Patientenzimmer",
                    "Room for inpatient care and recovery.", "Raum fuer stationaere Pflege.",
                    "RN_HLC", "RN_HLC_INP_GRP", ["M-HEL"]),
    RoomNameConcept("RN_HLC_RCV", "RN-05-10-02", "Recovery Room", "Aufwachraum",
                    "Room for post-procedure recovery.", "Raum fuer postoperative Ueberwachung.",
                    "RN_HLC", "RN_HLC_INP_GRP", ["M-HEL"]),
    # Healthcare — clinical (RN-05-20)
    RoomNameConcept("RN_HLC_TRT", "RN-05-20-01", "Treatment Room", "Behandlungsraum",
                    "Room for outpatient treatment.", "Raum fuer ambulante Behandlung.",
                    "RN_HLC", "RN_HLC_CLN_GRP", ["M-HEL"]),
    RoomNameConcept("RN_HLC_OR", "RN-05-20-02", "Operating Room", "Operationssaal",
                    "Room for surgical procedures.", "Raum fuer operative Eingriffe.",
                    "RN_HLC", "RN_HLC_CLN_GRP", ["M-HEL"]),
    RoomNameConcept("RN_HLC_PRM", "RN-05-20-03", "Procedure Room", "Eingriffsraum",
                    "Room for minor medical procedures.", "Raum fuer kleinere medizinische Eingriffe.",
                    "RN_HLC", "RN_HLC_CLN_GRP", ["M-HEL"]),
    RoomNameConcept("RN_HLC_EXM", "RN-05-20-04", "Examination Room", "Untersuchungsraum",
                    "Room for clinical examination.", "Raum fuer aerztliche Untersuchung.",
                    "RN_HLC", "RN_HLC_CLN_GRP", ["M-HEL"]),
    # Healthcare — diagnostics/support (RN-05-30)
    RoomNameConcept("RN_HLC_IMG", "RN-05-30-01", "Imaging Room", "Bildgebungsraum",
                    "Room for diagnostic imaging.", "Raum fuer diagnostische Bildgebung.",
                    "RN_HLC", "RN_HLC_SUP_GRP", ["M-HEL"]),
    RoomNameConcept("RN_HLC_LAB", "RN-05-30-02", "Medical Laboratory", "Medizinisches Labor",
                    "Laboratory for medical analysis.", "Labor fuer medizinische Analysen.",
                    "RN_HLC", "RN_HLC_SUP_GRP", ["M-HEL"]),
    RoomNameConcept("RN_HLC_WTR", "RN-05-30-03", "Waiting Room", "Wartezimmer",
                    "Room for patients and visitors to wait.", "Raum fuer wartende Patienten und Besucher.",
                    "RN_HLC", "RN_HLC_SUP_GRP", ["M-HEL"]),
    RoomNameConcept("RN_HLC_NRS", "RN-05-30-04", "Nurses Station", "Pflegestationszimmer",
                    "Central nursing and monitoring workspace.", "Zentrale Pflegestation.",
                    "RN_HLC", "RN_HLC_SUP_GRP", ["M-HEL"]),
    # Education — instruction (RN-06-10)
    RoomNameConcept("RN_LRN_CLS", "RN-06-10-01", "Classroom", "Klassenzimmer",
                    "Room for school or group instruction.", "Raum fuer Schul- oder Gruppenunterricht.",
                    "RN_LRN", "RN_LRN_INS_GRP", ["M-LRN"]),
    RoomNameConcept("RN_LRN_LCT", "RN-06-10-02", "Lecture Hall", "Hoersaal",
                    "Room with fixed seating for lectures.", "Raum mit festem Gestuehl fuer Vorlesungen.",
                    "RN_LRN", "RN_LRN_INS_GRP", ["M-LRN"]),
    RoomNameConcept("RN_LRN_SEM", "RN-06-10-03", "Seminar Room", "Seminarraum",
                    "Room for seminars and workshops.", "Raum fuer Seminare und Workshops.",
                    "RN_LRN", "RN_LRN_INS_GRP", ["M-LRN"]),
    RoomNameConcept("RN_LRN_CMP", "RN-06-10-04", "Computer Lab", "Computerraum",
                    "Room with computer workstations for teaching.", "Raum mit Computerarbeitsplaetzen fuer Unterricht.",
                    "RN_LRN", "RN_LRN_INS_GRP", ["M-LRN"]),
    # Education — self-directed (RN-06-20)
    RoomNameConcept("RN_LRN_LIB", "RN-06-20-01", "Library Room", "Bibliotheksraum",
                    "Room for reading and library use.", "Raum fuer Lesen und Bibliotheksnutzung.",
                    "RN_LRN", "RN_LRN_STY_GRP", ["M-LRN"]),
    RoomNameConcept("RN_LRN_STU", "RN-06-20-02", "Study Room", "Lernraum",
                    "Room for self-directed study.", "Raum fuer selbststaendiges Lernen.",
                    "RN_LRN", "RN_LRN_STY_GRP", ["M-LRN"]),
    RoomNameConcept("RN_LRN_WRK", "RN-06-20-03", "Training Workshop", "Ausbildungswerkstatt",
                    "Room for practical skills training.", "Raum fuer praktische Ausbildung.",
                    "RN_LRN", "RN_LRN_STY_GRP", ["M-LRN"]),
    # Education — assembly/special (RN-06-30)
    RoomNameConcept("RN_LRN_AUS", "RN-06-30-01", "Auditorium", "Aula",
                    "Large assembly hall for events.", "Grosse Versammlungshalle fuer Veranstaltungen.",
                    "RN_LRN", "RN_LRN_ASM_GRP", ["M-LRN"]),
    RoomNameConcept("RN_LRN_ART", "RN-06-30-02", "Art Studio", "Kunstatelier",
                    "Room for visual arts instruction and practice.", "Raum fuer bildnerischen Unterricht.",
                    "RN_LRN", "RN_LRN_ASM_GRP", ["M-LRN"]),
    RoomNameConcept("RN_LRN_SCI", "RN-06-30-03", "Science Lab", "Naturwissenschaftslabor",
                    "Laboratory for science teaching.", "Labor fuer naturwissenschaftlichen Unterricht.",
                    "RN_LRN", "RN_LRN_ASM_GRP", ["M-LRN"]),
    # Commercial — dining (RN-07-10)
    RoomNameConcept("RN_COM_CAF", "RN-07-10-01", "Cafeteria", "Cafeteria",
                    "Self-service dining space.", "Selbstbedienungsgastronomie.",
                    "RN_COM", "RN_COM_DIN_GRP", ["M-COM"]),
    RoomNameConcept("RN_COM_RST", "RN-07-10-02", "Restaurant", "Restaurant",
                    "Full-service dining space.", "Bediente Gastronomie.",
                    "RN_COM", "RN_COM_DIN_GRP", ["M-COM"]),
    RoomNameConcept("RN_COM_BAR", "RN-07-10-03", "Bar", "Bar",
                    "Room for beverage service.", "Raum fuer Getraenkeausschank.",
                    "RN_COM", "RN_COM_DIN_GRP", ["M-COM"]),
    RoomNameConcept("RN_COM_FOD", "RN-07-10-04", "Food Court", "Food-Court",
                    "Shared dining area with multiple vendors.", "Gemeinsame Gastronomieflaeche mit mehreren Anbietern.",
                    "RN_COM", "RN_COM_DIN_GRP", ["M-COM"]),
    # Commercial — retail (RN-07-20)
    RoomNameConcept("RN_COM_RET", "RN-07-20-01", "Retail Space", "Verkaufsraum",
                    "Room for displaying and selling goods.", "Raum fuer Warenpraesentation und Verkauf.",
                    "RN_COM", "RN_COM_RET_GRP", ["M-COM"]),
    RoomNameConcept("RN_COM_SAL", "RN-07-20-02", "Sales Floor", "Verkaufsflaeche",
                    "Open retail sales area.", "Offene Verkaufsflaeche.",
                    "RN_COM", "RN_COM_RET_GRP", ["M-COM"]),
    RoomNameConcept("RN_COM_KSK", "RN-07-20-03", "Kiosk", "Kiosk",
                    "Small retail or service counter space.", "Kleiner Verkaufs- oder Servicebereich.",
                    "RN_COM", "RN_COM_RET_GRP", ["M-COM"]),
    RoomNameConcept("RN_COM_CUS", "RN-07-20-04", "Customer Service Area", "Kundenbetreuungsbereich",
                    "Area for customer assistance and service.", "Bereich fuer Kundenbetreuung.",
                    "RN_COM", "RN_COM_RET_GRP", ["M-COM"]),
    RoomNameConcept("RN_COM_EXH", "RN-07-20-05", "Exhibition Space", "Ausstellungsraum",
                    "Room for displays and exhibitions.", "Raum fuer Ausstellungen.",
                    "RN_COM", "RN_COM_RET_GRP", ["M-COM"]),
    # Commercial — hospitality (RN-07-30)
    RoomNameConcept("RN_COM_HTL", "RN-07-30-01", "Hotel Room", "Hotelzimmer",
                    "Guest accommodation room.", "Uebernachtungszimmer fuer Gaeste.",
                    "RN_COM", "RN_COM_HSP_GRP", ["M-COM"]),
    # Industrial — production (RN-08-10)
    RoomNameConcept("RN_IND_WRK", "RN-08-10-01", "Workshop", "Werkstatt",
                    "Room for manual fabrication and repair.", "Raum fuer manuelle Fertigung und Reparatur.",
                    "RN_IND", "RN_IND_PRD_GRP", ["M-WRK-PRD"]),
    RoomNameConcept("RN_IND_PRD", "RN-08-10-02", "Production Hall", "Produktionshalle",
                    "Hall for manufacturing processes.", "Halle fuer Produktionsprozesse.",
                    "RN_IND", "RN_IND_PRD_GRP", ["M-WRK-PRD"]),
    RoomNameConcept("RN_IND_ASM", "RN-08-10-03", "Assembly Area", "Montagebereich",
                    "Area for product assembly.", "Bereich fuer Montage.",
                    "RN_IND", "RN_IND_PRD_GRP", ["M-WRK-PRD"]),
    RoomNameConcept("RN_IND_PKG", "RN-08-10-04", "Packaging Area", "Verpackungsbereich",
                    "Area for packaging goods.", "Bereich fuer Verpackung.",
                    "RN_IND", "RN_IND_PRD_GRP", ["M-WRK-PRD"]),
    RoomNameConcept("RN_IND_CLN", "RN-08-10-05", "Clean Room", "Reinraum",
                    "Controlled-environment production room.", "Produktionsraum mit kontrollierter Umgebung.",
                    "RN_IND", "RN_IND_PRD_GRP", ["M-WRK-PRD"]),
    # Industrial — logistics (RN-08-20)
    RoomNameConcept("RN_IND_WHS", "RN-08-20-01", "Warehouse", "Lagerhalle",
                    "Room or hall for goods storage.", "Halle oder Raum fuer Warenlagerung.",
                    "RN_IND", "RN_IND_LOG_GRP", ["M-WRK-PRD"]),
    RoomNameConcept("RN_IND_LDK", "RN-08-20-02", "Loading Dock", "Laderampe",
                    "Area for loading and unloading goods.", "Bereich fuer Be- und Entladung.",
                    "RN_IND", "RN_IND_LOG_GRP", ["S-PRK-SVC"]),
    RoomNameConcept("RN_IND_QC", "RN-08-20-03", "Quality Control Room", "Qualitaetskontrollraum",
                    "Room for inspection and quality testing.", "Raum fuer Pruefung und Qualitaetskontrolle.",
                    "RN_IND", "RN_IND_LOG_GRP", ["M-WRK-PRD"]),
    RoomNameConcept("RN_IND_MNT", "RN-08-20-04", "Maintenance Bay", "Wartungsbucht",
                    "Bay for equipment maintenance.", "Bucht fuer Geraetewartung.",
                    "RN_IND", "RN_IND_LOG_GRP", ["M-WRK-PRD"]),
    # Industrial — special (RN-08-30)
    RoomNameConcept("RN_IND_YRD", "RN-08-30-01", "Covered Yard", "Ueberdachter Hof",
                    "Covered exterior work or storage yard modeled as space.", "Ueberdachter Aussenarbeits- oder Lagerhof als Raum modelliert.",
                    "RN_IND", "RN_IND_SPC_GRP", ["M-WRK-PRD"]),
    # Technical — HVAC (RN-09-10)
    RoomNameConcept("RN_TEC_HVC", "RN-09-10-01", "HVAC Plant Room", "HLK-Zentralraum",
                    "Room for heating, ventilation, and cooling plant.", "Raum fuer Heizungs-, Lueftungs- und Klimaanlagen.",
                    "RN_TEC", "RN_TEC_MEP_GRP", ["S-TEC"]),
    RoomNameConcept("RN_TEC_PMP", "RN-09-10-02", "Pump Room", "Pumpenraum",
                    "Room for pumps and fluid handling.", "Raum fuer Pumpen und Fluessigkeitstechnik.",
                    "RN_TEC", "RN_TEC_MEP_GRP", ["S-TEC"]),
    RoomNameConcept("RN_TEC_BOI", "RN-09-10-03", "Boiler Room", "Heizungsraum",
                    "Room for boilers and heat generation.", "Raum fuer Heizkessel und Waermeerzeugung.",
                    "RN_TEC", "RN_TEC_MEP_GRP", ["S-TEC"]),
    RoomNameConcept("RN_TEC_CHL", "RN-09-10-04", "Chiller Room", "Kaelteraum",
                    "Room for chillers and cooling plant.", "Raum fuer Kaelteanlagen.",
                    "RN_TEC", "RN_TEC_MEP_GRP", ["S-TEC"]),
    RoomNameConcept("RN_TEC_SPR", "RN-09-10-05", "Sprinkler Room", "Sprinklerraum",
                    "Room for fire suppression equipment.", "Raum fuer Sprinkler- und Loeschanlagen.",
                    "RN_TEC", "RN_TEC_MEP_GRP", ["S-TEC"]),
    # Technical — electrical/IT (RN-09-20)
    RoomNameConcept("RN_TEC_ELC", "RN-09-20-01", "Electrical Room", "Elektroraum",
                    "Room for electrical distribution equipment.", "Raum fuer elektrische Verteilung.",
                    "RN_TEC", "RN_TEC_ELC_GRP", ["S-TEC"]),
    RoomNameConcept("RN_TEC_SRV", "RN-09-20-02", "Server Room", "Serverraum",
                    "Room for IT and network equipment.", "Raum fuer IT- und Netzwerktechnik.",
                    "RN_TEC", "RN_TEC_ELC_GRP", ["S-TEC"]),
    RoomNameConcept("RN_TEC_GEN", "RN-09-20-03", "Generator Room", "Generatorraum",
                    "Room for backup power generation.", "Raum fuer Notstromaggregate.",
                    "RN_TEC", "RN_TEC_ELC_GRP", ["S-TEC"]),
    RoomNameConcept("RN_TEC_TRA", "RN-09-20-04", "Transformer Room", "Transformatorenraum",
                    "Room for electrical transformers.", "Raum fuer Transformatoren.",
                    "RN_TEC", "RN_TEC_ELC_GRP", ["S-TEC"]),
    RoomNameConcept("RN_TEC_COM", "RN-09-20-05", "Communications Room", "Kommunikationsraum",
                    "Room for telecom and low-voltage systems.", "Raum fuer Telekommunikations- und Schwachstromanlagen.",
                    "RN_TEC", "RN_TEC_ELC_GRP", ["S-TEC"]),
    # Technical — metering/waste (RN-09-30)
    RoomNameConcept("RN_TEC_MMR", "RN-09-30-01", "Meter Room", "Zaehlerraum",
                    "Room for utility metering equipment.", "Raum fuer Verbrauchszaehler.",
                    "RN_TEC", "RN_TEC_UTL_GRP", ["S-TEC"]),
    RoomNameConcept("RN_TEC_WST", "RN-09-30-02", "Waste Room", "Abfallraum",
                    "Room for waste collection and handling.", "Raum fuer Abfallsammlung.",
                    "RN_TEC", "RN_TEC_UTL_GRP", ["S-TEC"]),
    # Storage — general (RN-10-10)
    RoomNameConcept("RN_STO_GEN", "RN-10-10-01", "General Storage", "Allgemeiner Lagerraum",
                    "Room for general material storage.", "Raum fuer allgemeine Materiallagerung.",
                    "RN_STO", "RN_STO_GEN_GRP", ["S-STO-GEN"]),
    RoomNameConcept("RN_STO_SUP", "RN-10-10-02", "Supply Room", "Materialraum",
                    "Room for consumable supplies.", "Raum fuer Verbrauchsmaterial.",
                    "RN_STO", "RN_STO_GEN_GRP", ["S-STO-GEN"]),
    RoomNameConcept("RN_STO_EQP", "RN-10-10-03", "Equipment Storage", "Geraetelager",
                    "Storage for tools and equipment.", "Lager fuer Geraete und Werkzeuge.",
                    "RN_STO", "RN_STO_GEN_GRP", ["S-STO-GEN"]),
    RoomNameConcept("RN_STO_ULD", "RN-10-10-04", "Unloading Storage", "Annahmelager",
                    "Temporary storage at delivery point.", "Zwischenlager am Annahmeort.",
                    "RN_STO", "RN_STO_GEN_GRP", ["S-STO-GEN"]),
    RoomNameConcept("RN_STO_JAN", "RN-10-10-05", "Janitor Closet", "Hauswarteschrank",
                    "Small room for cleaning supplies and equipment.", "Kleiner Raum fuer Reinigungsmaterial.",
                    "RN_STO", "RN_STO_GEN_GRP", ["S-STO-GEN"]),
    # Storage — specialized (RN-10-20)
    RoomNameConcept("RN_STO_ARC", "RN-10-20-01", "Archive Room", "Archivraum",
                    "Room for document and record archives.", "Raum fuer Dokumenten- und Aktenarchive.",
                    "RN_STO", "RN_STO_SPC_GRP", ["S-STO-GEN"]),
    RoomNameConcept("RN_STO_MAL", "RN-10-20-02", "Mail Room", "Postraum",
                    "Room for incoming and outgoing mail.", "Raum fuer Postein- und -ausgang.",
                    "RN_STO", "RN_STO_SPC_GRP", ["S-STO-GEN"]),
    RoomNameConcept("RN_STO_COL", "RN-10-20-03", "Cold Storage", "Kuehlraum",
                    "Refrigerated storage room.", "Gekuehlter Lagerraum.",
                    "RN_STO", "RN_STO_SPC_GRP", ["S-STO-GEN"]),
    # Outdoor — platforms (RN-11-10)
    RoomNameConcept("RN_OUT_BLN", "RN-11-10-01", "Balcony", "Balkon",
                    "Exterior projecting platform accessed from inside.", "Vom Innern erschlossene Aussenplattform.",
                    "RN_OUT", "RN_OUT_PLT_GRP", ["O"]),
    RoomNameConcept("RN_OUT_TRR", "RN-11-10-02", "Terrace", "Terrasse",
                    "Exterior paved or decked platform.", "Aussenliegende Terrassenflaeche.",
                    "RN_OUT", "RN_OUT_PLT_GRP", ["O"]),
    RoomNameConcept("RN_OUT_PAT", "RN-11-10-03", "Patio", "Innenhof",
                    "Enclosed or semi-enclosed outdoor sitting area.", "Innenhof oder Patio.",
                    "RN_OUT", "RN_OUT_PLT_GRP", ["O-GRN-REC"]),
    # Outdoor — landscape (RN-11-20)
    RoomNameConcept("RN_OUT_GDN", "RN-11-20-01", "Garden Area", "Gartenflaeche",
                    "Landscaped outdoor area as space.", "Als Raum modellierte Gartenflaeche.",
                    "RN_OUT", "RN_OUT_LND_GRP", ["O-GRN-GDN"]),
    RoomNameConcept("RN_OUT_PLY", "RN-11-20-02", "Playground", "Spielplatz",
                    "Outdoor play area.", "Aussenliegender Spielbereich.",
                    "RN_OUT", "RN_OUT_LND_GRP", ["O-GRN-REC"]),
    RoomNameConcept("RN_OUT_SPL", "RN-11-20-03", "Pool Area", "Beckenflaeche",
                    "Outdoor pool or water feature area.", "Aussenliegende Becken- oder Wasserflaeche.",
                    "RN_OUT", "RN_OUT_LND_GRP", ["O-GRN-REC"]),
    # Outdoor — covered routes (RN-11-30)
    RoomNameConcept("RN_OUT_CWK", "RN-11-30-01", "Covered Walkway", "Ueberdachter Fussweg",
                    "Covered exterior pedestrian route.", "Ueberdachter Aussenweg fuer Fussgaenger.",
                    "RN_OUT", "RN_OUT_COV_GRP", ["O-CIR-PED"]),
    RoomNameConcept("RN_OUT_PRT", "RN-11-30-02", "Portico", "Portikus",
                    "Covered exterior entrance structure.", "Ueberdachter Aussenanbau am Eingang.",
                    "RN_OUT", "RN_OUT_COV_GRP", ["O-CIR-PED"]),
    # Void — vertical (RN-12-10)
    RoomNameConcept("RN_VOI_SHA", "RN-12-10-01", "Shaft", "Schacht",
                    "Vertical service or circulation shaft.", "Vertikaler Technik- oder Erschliessungsschacht.",
                    "RN_VOI", "RN_VOI_VRT_GRP", ["S-VOI-VRT"]),
    RoomNameConcept("RN_VOI_RIS", "RN-12-10-02", "Riser", "Steigzone",
                    "Vertical building services riser.", "Vertikale Gebaeudetechnik-Steigzone.",
                    "RN_VOI", "RN_VOI_VRT_GRP", ["S-VOI-VRT"]),
    # Void — plenums (RN-12-20)
    RoomNameConcept("RN_VOI_PLN", "RN-12-20-01", "Plenum", "Installationszwischenraum",
                    "Ceiling or floor service void.", "Installationshohlraum in Decke oder Boden.",
                    "RN_VOI", "RN_VOI_PLN_GRP", ["S-VOI-PLN"]),
    RoomNameConcept("RN_VOI_MCH", "RN-12-20-02", "Mechanical Void", "Technikhohlraum",
                    "Non-accessible mechanical void.", "Nicht begehbarer Technikhohlraum.",
                    "RN_VOI", "RN_VOI_PLN_GRP", ["S-VOI-PLN"]),
    RoomNameConcept("RN_VOI_AIR", "RN-12-20-03", "Air Space", "Luftraum",
                    "Non-occupiable air volume in the model.", "Nicht nutzbarer Luftraum im Modell.",
                    "RN_VOI", "RN_VOI_PLN_GRP", ["S-VOI"]),
    # Void — structural/special (RN-12-30)
    RoomNameConcept("RN_VOI_ATR", "RN-12-30-01", "Atrium Void", "Atrium",
                    "Multistory open interior volume.", "Mehrgeschossiger offener Innenraum.",
                    "RN_VOI", "RN_VOI_STR_GRP", ["S-VOI-MLT"]),
    RoomNameConcept("RN_VOI_STR", "RN-12-30-02", "Structural Void", "Konstruktionshohlraum",
                    "Void within structural elements.", "Hohlraum in tragenden Bauteilen.",
                    "RN_VOI", "RN_VOI_STR_GRP", ["S-VOI-STR"]),
    RoomNameConcept("RN_VOI_PRK", "RN-12-30-03", "Interior Parking Stall", "Innenparkierplatz",
                    "Individual parking space within a structure.", "Einzelner Parkierplatz in geschlossener Anlage.",
                    "RN_VOI", "RN_VOI_STR_GRP", ["S-PRK-INT"]),
]

# v1 mnemonic notation → v2 numeric notation (includes removed RN-CIR-AIS → COR).
NOTATION_V1_TO_V2: dict[str, str] = {
    "RN-RES-BED": "RN-01-10-01",
    "RN-RES-LIV": "RN-01-10-02",
    "RN-RES-DIN": "RN-01-10-03",
    "RN-RES-STU": "RN-01-10-04",
    "RN-RES-GST": "RN-01-10-05",
    "RN-RES-KIT": "RN-01-20-01",
    "RN-RES-BTH": "RN-01-20-02",
    "RN-RES-LAU": "RN-01-20-03",
    "RN-RES-UTL": "RN-01-20-04",
    "RN-RES-ENT": "RN-01-30-01",
    "RN-RES-CLO": "RN-01-30-02",
    "RN-RES-APT": "RN-01-30-03",
    "RN-WRK-OFF": "RN-02-10-01",
    "RN-WRK-OPN": "RN-02-10-02",
    "RN-WRK-FCS": "RN-02-10-03",
    "RN-WRK-PHN": "RN-02-10-04",
    "RN-WRK-COW": "RN-02-10-05",
    "RN-WRK-MTG": "RN-02-20-01",
    "RN-WRK-CNF": "RN-02-20-02",
    "RN-WRK-BRK": "RN-02-20-03",
    "RN-WRK-REC": "RN-02-30-01",
    "RN-WRK-ADM": "RN-02-30-02",
    "RN-WRK-MNG": "RN-02-30-03",
    "RN-WRK-OAD": "RN-02-30-04",
    "RN-CIR-COR": "RN-03-10-01",
    "RN-CIR-AIS": "RN-03-10-01",
    "RN-CIR-LOB": "RN-03-10-02",
    "RN-CIR-ENT": "RN-03-10-03",
    "RN-CIR-VES": "RN-03-10-04",
    "RN-CIR-STR": "RN-03-20-01",
    "RN-CIR-ELV": "RN-03-20-02",
    "RN-CIR-RAM": "RN-03-20-03",
    "RN-CIR-LND": "RN-03-20-04",
    "RN-CIR-GAL": "RN-03-30-01",
    "RN-HYG-WC-M": "RN-04-10-01",
    "RN-HYG-WC-F": "RN-04-10-02",
    "RN-HYG-WC-IV": "RN-04-10-03",
    "RN-HYG-WC-MIX": "RN-04-10-04",
    "RN-HYG-SHW": "RN-04-20-01",
    "RN-HYG-CHG": "RN-04-20-02",
    "RN-HYG-LCK": "RN-04-20-03",
    "RN-HYG-GRD": "RN-04-30-01",
    "RN-HLC-PAT": "RN-05-10-01",
    "RN-HLC-RCV": "RN-05-10-02",
    "RN-HLC-TRT": "RN-05-20-01",
    "RN-HLC-OR": "RN-05-20-02",
    "RN-HLC-PRM": "RN-05-20-03",
    "RN-HLC-EXM": "RN-05-20-04",
    "RN-HLC-IMG": "RN-05-30-01",
    "RN-HLC-LAB": "RN-05-30-02",
    "RN-HLC-WTR": "RN-05-30-03",
    "RN-HLC-NRS": "RN-05-30-04",
    "RN-LRN-CLS": "RN-06-10-01",
    "RN-LRN-LCT": "RN-06-10-02",
    "RN-LRN-SEM": "RN-06-10-03",
    "RN-LRN-CMP": "RN-06-10-04",
    "RN-LRN-LIB": "RN-06-20-01",
    "RN-LRN-STU": "RN-06-20-02",
    "RN-LRN-WRK": "RN-06-20-03",
    "RN-LRN-AUS": "RN-06-30-01",
    "RN-LRN-ART": "RN-06-30-02",
    "RN-LRN-SCI": "RN-06-30-03",
    "RN-COM-CAF": "RN-07-10-01",
    "RN-COM-RST": "RN-07-10-02",
    "RN-COM-BAR": "RN-07-10-03",
    "RN-COM-FOD": "RN-07-10-04",
    "RN-COM-RET": "RN-07-20-01",
    "RN-COM-SAL": "RN-07-20-02",
    "RN-COM-KSK": "RN-07-20-03",
    "RN-COM-CUS": "RN-07-20-04",
    "RN-COM-EXH": "RN-07-20-05",
    "RN-COM-HTL": "RN-07-30-01",
    "RN-IND-WRK": "RN-08-10-01",
    "RN-IND-PRD": "RN-08-10-02",
    "RN-IND-ASM": "RN-08-10-03",
    "RN-IND-PKG": "RN-08-10-04",
    "RN-IND-CLN": "RN-08-10-05",
    "RN-IND-WHS": "RN-08-20-01",
    "RN-IND-LDK": "RN-08-20-02",
    "RN-IND-QC": "RN-08-20-03",
    "RN-IND-MNT": "RN-08-20-04",
    "RN-IND-YRD": "RN-08-30-01",
    "RN-TEC-HVC": "RN-09-10-01",
    "RN-TEC-PMP": "RN-09-10-02",
    "RN-TEC-BOI": "RN-09-10-03",
    "RN-TEC-CHL": "RN-09-10-04",
    "RN-TEC-SPR": "RN-09-10-05",
    "RN-TEC-ELC": "RN-09-20-01",
    "RN-TEC-SRV": "RN-09-20-02",
    "RN-TEC-GEN": "RN-09-20-03",
    "RN-TEC-TRA": "RN-09-20-04",
    "RN-TEC-COM": "RN-09-20-05",
    "RN-TEC-MMR": "RN-09-30-01",
    "RN-TEC-WST": "RN-09-30-02",
    "RN-STO-GEN": "RN-10-10-01",
    "RN-STO-SUP": "RN-10-10-02",
    "RN-STO-EQP": "RN-10-10-03",
    "RN-STO-ULD": "RN-10-10-04",
    "RN-STO-JAN": "RN-10-10-05",
    "RN-STO-ARC": "RN-10-20-01",
    "RN-STO-MAL": "RN-10-20-02",
    "RN-STO-COL": "RN-10-20-03",
    "RN-OUT-BLN": "RN-11-10-01",
    "RN-OUT-TRR": "RN-11-10-02",
    "RN-OUT-PAT": "RN-11-10-03",
    "RN-OUT-GDN": "RN-11-20-01",
    "RN-OUT-PLY": "RN-11-20-02",
    "RN-OUT-SPL": "RN-11-20-03",
    "RN-OUT-CWK": "RN-11-30-01",
    "RN-OUT-PRT": "RN-11-30-02",
    "RN-VOI-SHA": "RN-12-10-01",
    "RN-VOI-RIS": "RN-12-10-02",
    "RN-VOI-PLN": "RN-12-20-01",
    "RN-VOI-MCH": "RN-12-20-02",
    "RN-VOI-AIR": "RN-12-20-03",
    "RN-VOI-ATR": "RN-12-30-01",
    "RN-VOI-STR": "RN-12-30-02",
    "RN-VOI-PRK": "RN-12-30-03",
}

NOTATION_TO_LOCAL: dict[str, str] = {c.notation: c.local_name for c in CONCEPTS}


def activity_local_name(code: str) -> str:
    return code.replace("-", "_")


def enum_key_from_notation(notation: str) -> str:
    return notation.lower().replace("-", "_")


def ttl_escape(value: str) -> str:
    return value.replace("\\", "\\\\").replace('"', '\\"')
