"""Source data for abstract building space name classification."""

from __future__ import annotations

from dataclasses import dataclass, field

RN_NS = "https://example.org/abstract/building-space-name-classification/"
ABS_NS = "https://example.org/abstract/building-space-activity-classification/"


@dataclass(frozen=True)
class RoomNameConcept:
    local_name: str
    notation: str
    label_en: str
    label_de: str
    definition_en: str
    definition_de: str
    category: str
    activity_codes: list[str] = field(default_factory=list)


@dataclass(frozen=True)
class RoomNameCategory:
    local_name: str
    notation: str
    label_en: str
    label_de: str
    definition_en: str
    definition_de: str


CATEGORIES: list[RoomNameCategory] = [
    RoomNameCategory("RN_RES", "RN_RES", "Residential Room Names", "Wohnraumbezeichnungen",
                     "Normalized room names for residential living spaces.",
                     "Normalisierte Raumbezeichnungen fuer Wohnnutzungen."),
    RoomNameCategory("RN_WRK", "RN_WRK", "Work Room Names", "Arbeitsraumbezeichnungen",
                     "Normalized room names for office and knowledge work.",
                     "Normalisierte Raumbezeichnungen fuer Buero- und Wissensarbeit."),
    RoomNameCategory("RN_CIR", "RN_CIR", "Circulation Room Names", "Erschliessungsraumbezeichnungen",
                     "Normalized room names for circulation and access spaces.",
                     "Normalisierte Raumbezeichnungen fuer Erschliessungsraeume."),
    RoomNameCategory("RN_HYG", "RN_HYG", "Hygiene Room Names", "Hygieneraumbezeichnungen",
                     "Normalized room names for sanitary and changing spaces.",
                     "Normalisierte Raumbezeichnungen fuer Hygiene- und Sanitaerraeume."),
    RoomNameCategory("RN_HLC", "RN_HLC", "Healthcare Room Names", "Gesundheitsraumbezeichnungen",
                     "Normalized room names for medical and care spaces.",
                     "Normalisierte Raumbezeichnungen fuer medizinische und pflegerische Raeume."),
    RoomNameCategory("RN_LRN", "RN_LRN", "Education Room Names", "Bildungsraumbezeichnungen",
                     "Normalized room names for teaching and learning spaces.",
                     "Normalisierte Raumbezeichnungen fuer Bildungs- und Lernraeume."),
    RoomNameCategory("RN_COM", "RN_COM", "Commercial Room Names", "Gewerberaumbezeichnungen",
                     "Normalized room names for hospitality and retail spaces.",
                     "Normalisierte Raumbezeichnungen fuer Gastronomie- und Verkaufsraeume."),
    RoomNameCategory("RN_IND", "RN_IND", "Industrial Room Names", "Industrieraumbezeichnungen",
                     "Normalized room names for production and workshop spaces.",
                     "Normalisierte Raumbezeichnungen fuer Produktions- und Werkraeume."),
    RoomNameCategory("RN_TEC", "RN_TEC", "Technical Room Names", "Technikraumbezeichnungen",
                     "Normalized room names for building services and plant rooms.",
                     "Normalisierte Raumbezeichnungen fuer Technik- und Anlagenraeume."),
    RoomNameCategory("RN_STO", "RN_STO", "Storage Room Names", "Lagerraumbezeichnungen",
                     "Normalized room names for storage and ancillary spaces.",
                     "Normalisierte Raumbezeichnungen fuer Lager- und Nebenraeume."),
    RoomNameCategory("RN_OUT", "RN_OUT", "Outdoor Room Names", "Aussenraumbezeichnungen",
                     "Normalized room names for exterior spaces modeled as IfcSpace.",
                     "Normalisierte Raumbezeichnungen fuer als IfcSpace modellierte Aussenraeume."),
    RoomNameCategory("RN_VOI", "RN_VOI", "Void Room Names", "Hohlraumbezeichnungen",
                     "Normalized room names for non-occupiable void and special spaces.",
                     "Normalisierte Raumbezeichnungen fuer nicht nutzbare Hohl- und Sonderraeume."),
]

# Default activity mapping by category prefix (overridden per concept when activity_codes set).
CATEGORY_ACTIVITY_DEFAULTS: dict[str, str] = {
    "RN_RES": "M-RES",
    "RN_WRK": "M-WRK-KNW",
    "RN_CIR": "S-CIR-HOR",
    "RN_HYG": "S-HYG",
    "RN_HLC": "M-HEL",
    "RN_LRN": "M-LRN",
    "RN_COM": "M-COM",
    "RN_IND": "M-WRK-PRD",
    "RN_TEC": "S-TEC",
    "RN_STO": "S-STO-GEN",
    "RN_OUT": "O",
    "RN_VOI": "S-VOI",
}

CONCEPTS: list[RoomNameConcept] = [
    # Residential (12)
    RoomNameConcept("RN_RES_BED", "RN-RES-BED", "Bedroom", "Schlafzimmer",
                    "Room primarily used for sleeping.", "Raum primaer fuer Schlafen.",
                    "RN_RES", ["M-RES"]),
    RoomNameConcept("RN_RES_LIV", "RN-RES-LIV", "Living Room", "Wohnzimmer",
                    "Room for daily living and relaxation.", "Raum fuer Wohnen und Entspannung.",
                    "RN_RES", ["M-RES"]),
    RoomNameConcept("RN_RES_DIN", "RN-RES-DIN", "Dining Room", "Esszimmer",
                    "Room for eating meals.", "Raum fuer Mahlzeiten.",
                    "RN_RES", ["M-RES"]),
    RoomNameConcept("RN_RES_KIT", "RN-RES-KIT", "Kitchen", "Kueche",
                    "Room for food preparation.", "Raum fuer Speisezubereitung.",
                    "RN_RES", ["M-RES"]),
    RoomNameConcept("RN_RES_BTH", "RN-RES-BTH", "Bathroom", "Badezimmer",
                    "Room with bath, shower, or personal hygiene fixtures.", "Raum mit Bad, Dusche oder Koerperpflege.",
                    "RN_RES", ["M-RES"]),
    RoomNameConcept("RN_RES_LAU", "RN-RES-LAU", "Laundry Room", "Waschkueche",
                    "Room for washing and drying clothes.", "Raum fuer Waeschepflege.",
                    "RN_RES", ["M-RES"]),
    RoomNameConcept("RN_RES_STU", "RN-RES-STU", "Home Study", "Arbeitszimmer",
                    "Residential room for study or home office work.", "Wohnlicher Raum fuer Arbeit oder Studium.",
                    "RN_RES", ["M-RES"]),
    RoomNameConcept("RN_RES_ENT", "RN-RES-ENT", "Residential Entry", "Wohnungseingang",
                    "Entry space within a dwelling unit.", "Eingangsbereich innerhalb einer Wohneinheit.",
                    "RN_RES", ["M-RES"]),
    RoomNameConcept("RN_RES_CLO", "RN-RES-CLO", "Residential Closet", "Abstellraum Wohnen",
                    "Small storage within a dwelling unit.", "Kleiner Abstellraum innerhalb einer Wohneinheit.",
                    "RN_RES", ["M-RES"]),
    RoomNameConcept("RN_RES_GST", "RN-RES-GST", "Guest Room", "Gaestezimmer",
                    "Room for overnight guests.", "Raum fuer ueber Nacht bleibende Gaeste.",
                    "RN_RES", ["M-RES"]),
    RoomNameConcept("RN_RES_UTL", "RN-RES-UTL", "Utility Room", "Hauswirtschaftsraum",
                    "Room for domestic utilities and equipment.", "Raum fuer haushaltstechnische Einrichtungen.",
                    "RN_RES", ["M-RES"]),
    RoomNameConcept("RN_RES_APT", "RN-RES-APT", "Apartment Unit", "Wohneinheit",
                    "Generic residential unit space when not subdivided further.", "Generische Wohneinheit ohne weitere Unterteilung.",
                    "RN_RES", ["M-RES"]),
    # Work (12)
    RoomNameConcept("RN_WRK_OFF", "RN-WRK-OFF", "Office", "Buero",
                    "Enclosed office for individual or shared desk work.", "Buero fuer Einzel- oder Gruppenarbeit.",
                    "RN_WRK", ["M-WRK-KNW"]),
    RoomNameConcept("RN_WRK_OPN", "RN-WRK-OPN", "Open-Plan Office", "Grossraumbuero",
                    "Open office landscape without full-height partitions.", "Offene Burolandschaft ohne geschlossene Zellbueros.",
                    "RN_WRK", ["M-WRK-KNW"]),
    RoomNameConcept("RN_WRK_MTG", "RN-WRK-MTG", "Meeting Room", "Besprechungsraum",
                    "Room for small group meetings.", "Raum fuer kleine Besprechungen.",
                    "RN_WRK", ["M-WRK-KNW"]),
    RoomNameConcept("RN_WRK_CNF", "RN-WRK-CNF", "Conference Room", "Konferenzraum",
                    "Room for formal meetings and presentations.", "Raum fuer formelle Sitzungen und Praesentationen.",
                    "RN_WRK", ["M-WRK-KNW"]),
    RoomNameConcept("RN_WRK_FCS", "RN-WRK-FCS", "Focus Room", "Fokusraum",
                    "Small room for concentrated individual work.", "Kleiner Raum fuer konzentrierte Einzelarbeit.",
                    "RN_WRK", ["M-WRK-KNW"]),
    RoomNameConcept("RN_WRK_PHN", "RN-WRK-PHN", "Phone Booth", "Telefonbox",
                    "Small enclosure for private calls.", "Kleine Kabine fuer Telefongespraeche.",
                    "RN_WRK", ["M-WRK-KNW"]),
    RoomNameConcept("RN_WRK_BRK", "RN-WRK-BRK", "Break Room", "Pausenraum",
                    "Informal staff rest and refreshment space.", "Informeller Raum fuer Pausen.",
                    "RN_WRK", ["M-WRK-KNW"]),
    RoomNameConcept("RN_WRK_REC", "RN-WRK-REC", "Reception", "Empfang",
                    "Visitor reception and waiting area.", "Empfang und Wartebereich fuer Besucher.",
                    "RN_WRK", ["M-WRK-KNW"]),
    RoomNameConcept("RN_WRK_ADM", "RN-WRK-ADM", "Administrative Office", "Verwaltungsbuero",
                    "Office for administrative staff.", "Buero fuer Verwaltungspersonal.",
                    "RN_WRK", ["M-WRK-KNW"]),
    RoomNameConcept("RN_WRK_MNG", "RN-WRK-MNG", "Manager Office", "Fuehrungsbuero",
                    "Office for management roles.", "Buero fuer Fuehrungsfunktionen.",
                    "RN_WRK", ["M-WRK-KNW"]),
    RoomNameConcept("RN_WRK_COW", "RN-WRK-COW", "Coworking Space", "Coworking-Flaeche",
                    "Shared flexible workspace.", "Gemeinschaftlich genutzter flexibler Arbeitsraum.",
                    "RN_WRK", ["M-WRK-KNW"]),
    RoomNameConcept("RN_WRK_OAD", "RN-WRK-OAD", "Open Administrative Area", "Offene Verwaltungsflaeche",
                    "Open administrative work area.", "Offene Verwaltungsarbeitsflaeche.",
                    "RN_WRK", ["M-WRK-KNW"]),
    # Circulation (10)
    RoomNameConcept("RN_CIR_COR", "RN-CIR-COR", "Corridor", "Korridor",
                    "Horizontal circulation passage.", "Horizontaler Verbindungsgang.",
                    "RN_CIR", ["S-CIR-HOR"]),
    RoomNameConcept("RN_CIR_LOB", "RN-CIR-LOB", "Lobby", "Eingangshalle",
                    "Main entrance lobby or reception hall.", "Eingangshalle oder Empfoyer.",
                    "RN_CIR", ["S-CIR-HOR", "M-CIR"]),
    RoomNameConcept("RN_CIR_ENT", "RN-CIR-ENT", "Entrance Hall", "Entree",
                    "Building entrance transition space.", "Uebergangsraum am Gebaeudeeingang.",
                    "RN_CIR", ["S-CIR-HOR"]),
    RoomNameConcept("RN_CIR_STR", "RN-CIR-STR", "Stairwell", "Treppenhaus",
                    "Enclosed stair and landing volume.", "Treppenhaus mit Podesten.",
                    "RN_CIR", ["S-CIR-VRT-MAN"]),
    RoomNameConcept("RN_CIR_ELV", "RN-CIR-ELV", "Elevator Lobby", "Aufzugszone",
                    "Waiting area at elevator stops.", "Wartebereich an Aufzugshaltestellen.",
                    "RN_CIR", ["S-CIR-VRT-MEC"]),
    RoomNameConcept("RN_CIR_RAM", "RN-CIR-RAM", "Ramp", "Rampe",
                    "Inclined accessible circulation route.", "Geneigte barrierefreie Erschliessung.",
                    "RN_CIR", ["S-CIR-VRT-MAN"]),
    RoomNameConcept("RN_CIR_LND", "RN-CIR-LND", "Landing", "Podest",
                    "Stair or ramp landing platform.", "Treppen- oder Rampenpodest.",
                    "RN_CIR", ["S-CIR-VRT-MAN"]),
    RoomNameConcept("RN_CIR_AIS", "RN-CIR-AIS", "Aisle", "Gang",
                    "Narrow passage between rows or functions.", "Schmaler Durchgang zwischen Reihen oder Funktionen.",
                    "RN_CIR", ["S-CIR-HOR"]),
    RoomNameConcept("RN_CIR_VES", "RN-CIR-VES", "Vestibule", "Vorraum",
                    "Transition space between exterior and interior.", "Uebergangsraum zwischen Aussen und Innen.",
                    "RN_CIR", ["S-CIR-HOR"]),
    RoomNameConcept("RN_CIR_GAL", "RN-CIR-GAL", "Gallery", "Galerie",
                    "Circulation gallery integral to main activity.", "Erschliessungsgalerie als Teil der Hauptnutzung.",
                    "RN_CIR", ["M-CIR"]),
    # Hygiene (8)
    RoomNameConcept("RN_HYG_WC_M", "RN-HYG-WC-M", "Male Toilet", "Herren-WC",
                    "Toilet room for male use.", "WC fuer Maenner.",
                    "RN_HYG", ["S-HYG-WC-M"]),
    RoomNameConcept("RN_HYG_WC_F", "RN-HYG-WC-F", "Female Toilet", "Damen-WC",
                    "Toilet room for female use.", "WC fuer Frauen.",
                    "RN_HYG", ["S-HYG-WC-F"]),
    RoomNameConcept("RN_HYG_WC_IV", "RN-HYG-WC-IV", "Accessible Toilet", "Barrierefreies WC",
                    "Wheelchair-accessible toilet room.", "Rollstuhlgaengiges WC.",
                    "RN_HYG", ["S-HYG-WC-IV"]),
    RoomNameConcept("RN_HYG_WC_MIX", "RN-HYG-WC-MIX", "Unisex Toilet", "Allgemeines WC",
                    "Toilet room for mixed or all-gender use.", "WC fuer gemischte oder all-gender Nutzung.",
                    "RN_HYG", ["S-HYG-WC-MIX"]),
    RoomNameConcept("RN_HYG_SHW", "RN-HYG-SHW", "Shower Room", "Duschraum",
                    "Room with shower facilities.", "Raum mit Duscheinrichtungen.",
                    "RN_HYG", ["S-HYG-SHW"]),
    RoomNameConcept("RN_HYG_CHG", "RN-HYG-CHG", "Changing Room", "Umkleideraum",
                    "Room for changing clothes.", "Raum zum Umziehen.",
                    "RN_HYG", ["S-HYG-SHW"]),
    RoomNameConcept("RN_HYG_LCK", "RN-HYG-LCK", "Locker Room", "Schliessfachraum",
                    "Room with personal lockers.", "Raum mit persoenlichen Schliessfaechern.",
                    "RN_HYG", ["S-STO-LCK"]),
    RoomNameConcept("RN_HYG_GRD", "RN-HYG-GRD", "Cloakroom", "Garderobe",
                    "Staffed or unstaffed coat check at entry.", "Garderobe mit oder ohne Bedienung am Eingang.",
                    "RN_HYG", ["S-HYG-GRD"]),
    # Healthcare (10)
    RoomNameConcept("RN_HLC_PAT", "RN-HLC-PAT", "Patient Room", "Patientenzimmer",
                    "Room for inpatient care and recovery.", "Raum fuer stationaere Pflege.",
                    "RN_HLC", ["M-HEL"]),
    RoomNameConcept("RN_HLC_TRT", "RN-HLC-TRT", "Treatment Room", "Behandlungsraum",
                    "Room for outpatient treatment.", "Raum fuer ambulante Behandlung.",
                    "RN_HLC", ["M-HEL"]),
    RoomNameConcept("RN_HLC_OR", "RN-HLC-OR", "Operating Room", "Operationssaal",
                    "Room for surgical procedures.", "Raum fuer operative Eingriffe.",
                    "RN_HLC", ["M-HEL"]),
    RoomNameConcept("RN_HLC_RCV", "RN-HLC-RCV", "Recovery Room", "Aufwachraum",
                    "Room for post-procedure recovery.", "Raum fuer postoperative Ueberwachung.",
                    "RN_HLC", ["M-HEL"]),
    RoomNameConcept("RN_HLC_IMG", "RN-HLC-IMG", "Imaging Room", "Bildgebungsraum",
                    "Room for diagnostic imaging.", "Raum fuer diagnostische Bildgebung.",
                    "RN_HLC", ["M-HEL"]),
    RoomNameConcept("RN_HLC_LAB", "RN-HLC-LAB", "Medical Laboratory", "Medizinisches Labor",
                    "Laboratory for medical analysis.", "Labor fuer medizinische Analysen.",
                    "RN_HLC", ["M-HEL"]),
    RoomNameConcept("RN_HLC_EXM", "RN-HLC-EXM", "Examination Room", "Untersuchungsraum",
                    "Room for clinical examination.", "Raum fuer aerztliche Untersuchung.",
                    "RN_HLC", ["M-HEL"]),
    RoomNameConcept("RN_HLC_WTR", "RN-HLC-WTR", "Waiting Room", "Wartezimmer",
                    "Room for patients and visitors to wait.", "Raum fuer wartende Patienten und Besucher.",
                    "RN_HLC", ["M-HEL"]),
    RoomNameConcept("RN_HLC_NRS", "RN-HLC-NRS", "Nurses Station", "Pflegestationszimmer",
                    "Central nursing and monitoring workspace.", "Zentrale Pflegestation.",
                    "RN_HLC", ["M-HEL"]),
    RoomNameConcept("RN_HLC_PRM", "RN-HLC-PRM", "Procedure Room", "Eingriffsraum",
                    "Room for minor medical procedures.", "Raum fuer kleinere medizinische Eingriffe.",
                    "RN_HLC", ["M-HEL"]),
    # Education (10)
    RoomNameConcept("RN_LRN_CLS", "RN-LRN-CLS", "Classroom", "Klassenzimmer",
                    "Room for school or group instruction.", "Raum fuer Schul- oder Gruppenunterricht.",
                    "RN_LRN", ["M-LRN"]),
    RoomNameConcept("RN_LRN_LCT", "RN-LRN-LCT", "Lecture Hall", "Hoersaal",
                    "Room with fixed seating for lectures.", "Raum mit festem Gestuehl fuer Vorlesungen.",
                    "RN_LRN", ["M-LRN"]),
    RoomNameConcept("RN_LRN_SEM", "RN-LRN-SEM", "Seminar Room", "Seminarraum",
                    "Room for seminars and workshops.", "Raum fuer Seminare und Workshops.",
                    "RN_LRN", ["M-LRN"]),
    RoomNameConcept("RN_LRN_LIB", "RN-LRN-LIB", "Library Room", "Bibliotheksraum",
                    "Room for reading and library use.", "Raum fuer Lesen und Bibliotheksnutzung.",
                    "RN_LRN", ["M-LRN"]),
    RoomNameConcept("RN_LRN_CMP", "RN-LRN-CMP", "Computer Lab", "Computerraum",
                    "Room with computer workstations for teaching.", "Raum mit Computerarbeitsplaetzen fuer Unterricht.",
                    "RN_LRN", ["M-LRN"]),
    RoomNameConcept("RN_LRN_STU", "RN-LRN-STU", "Study Room", "Lernraum",
                    "Room for self-directed study.", "Raum fuer selbststaendiges Lernen.",
                    "RN_LRN", ["M-LRN"]),
    RoomNameConcept("RN_LRN_WRK", "RN-LRN-WRK", "Training Workshop", "Ausbildungswerkstatt",
                    "Room for practical skills training.", "Raum fuer praktische Ausbildung.",
                    "RN_LRN", ["M-LRN"]),
    RoomNameConcept("RN_LRN_AUS", "RN-LRN-AUS", "Auditorium", "Aula",
                    "Large assembly hall for events.", "Grosse Versammlungshalle fuer Veranstaltungen.",
                    "RN_LRN", ["M-LRN"]),
    RoomNameConcept("RN_LRN_ART", "RN-LRN-ART", "Art Studio", "Kunstatelier",
                    "Room for visual arts instruction and practice.", "Raum fuer bildnerischen Unterricht.",
                    "RN_LRN", ["M-LRN"]),
    RoomNameConcept("RN_LRN_SCI", "RN-LRN-SCI", "Science Lab", "Naturwissenschaftslabor",
                    "Laboratory for science teaching.", "Labor fuer naturwissenschaftlichen Unterricht.",
                    "RN_LRN", ["M-LRN"]),
    # Commercial (10)
    RoomNameConcept("RN_COM_CAF", "RN-COM-CAF", "Cafeteria", "Cafeteria",
                    "Self-service dining space.", "Selbstbedienungsgastronomie.",
                    "RN_COM", ["M-COM"]),
    RoomNameConcept("RN_COM_RST", "RN-COM-RST", "Restaurant", "Restaurant",
                    "Full-service dining space.", "Bediente Gastronomie.",
                    "RN_COM", ["M-COM"]),
    RoomNameConcept("RN_COM_RET", "RN-COM-RET", "Retail Space", "Verkaufsraum",
                    "Room for displaying and selling goods.", "Raum fuer Warenpraesentation und Verkauf.",
                    "RN_COM", ["M-COM"]),
    RoomNameConcept("RN_COM_HTL", "RN-COM-HTL", "Hotel Room", "Hotelzimmer",
                    "Guest accommodation room.", "Uebernachtungszimmer fuer Gaeste.",
                    "RN_COM", ["M-COM"]),
    RoomNameConcept("RN_COM_BAR", "RN-COM-BAR", "Bar", "Bar",
                    "Room for beverage service.", "Raum fuer Getraenkeausschank.",
                    "RN_COM", ["M-COM"]),
    RoomNameConcept("RN_COM_KSK", "RN-COM-KSK", "Kiosk", "Kiosk",
                    "Small retail or service counter space.", "Kleiner Verkaufs- oder Servicebereich.",
                    "RN_COM", ["M-COM"]),
    RoomNameConcept("RN_COM_EXH", "RN-COM-EXH", "Exhibition Space", "Ausstellungsraum",
                    "Room for displays and exhibitions.", "Raum fuer Ausstellungen.",
                    "RN_COM", ["M-COM"]),
    RoomNameConcept("RN_COM_SAL", "RN-COM-SAL", "Sales Floor", "Verkaufsflaeche",
                    "Open retail sales area.", "Offene Verkaufsflaeche.",
                    "RN_COM", ["M-COM"]),
    RoomNameConcept("RN_COM_CUS", "RN-COM-CUS", "Customer Service Area", "Kundenbetreuungsbereich",
                    "Area for customer assistance and service.", "Bereich fuer Kundenbetreuung.",
                    "RN_COM", ["M-COM"]),
    RoomNameConcept("RN_COM_FOD", "RN-COM-FOD", "Food Court", "Food-Court",
                    "Shared dining area with multiple vendors.", "Gemeinsame Gastronomieflaeche mit mehreren Anbietern.",
                    "RN_COM", ["M-COM"]),
    # Industrial (10)
    RoomNameConcept("RN_IND_WRK", "RN-IND-WRK", "Workshop", "Werkstatt",
                    "Room for manual fabrication and repair.", "Raum fuer manuelle Fertigung und Reparatur.",
                    "RN_IND", ["M-WRK-PRD"]),
    RoomNameConcept("RN_IND_WHS", "RN-IND-WHS", "Warehouse", "Lagerhalle",
                    "Room or hall for goods storage.", "Halle oder Raum fuer Warenlagerung.",
                    "RN_IND", ["M-WRK-PRD"]),
    RoomNameConcept("RN_IND_LDK", "RN-IND-LDK", "Loading Dock", "Laderampe",
                    "Area for loading and unloading goods.", "Bereich fuer Be- und Entladung.",
                    "RN_IND", ["S-PRK-SVC"]),
    RoomNameConcept("RN_IND_PRD", "RN-IND-PRD", "Production Hall", "Produktionshalle",
                    "Hall for manufacturing processes.", "Halle fuer Produktionsprozesse.",
                    "RN_IND", ["M-WRK-PRD"]),
    RoomNameConcept("RN_IND_ASM", "RN-IND-ASM", "Assembly Area", "Montagebereich",
                    "Area for product assembly.", "Bereich fuer Montage.",
                    "RN_IND", ["M-WRK-PRD"]),
    RoomNameConcept("RN_IND_QC", "RN-IND-QC", "Quality Control Room", "Qualitaetskontrollraum",
                    "Room for inspection and quality testing.", "Raum fuer Pruefung und Qualitaetskontrolle.",
                    "RN_IND", ["M-WRK-PRD"]),
    RoomNameConcept("RN_IND_PKG", "RN-IND-PKG", "Packaging Area", "Verpackungsbereich",
                    "Area for packaging goods.", "Bereich fuer Verpackung.",
                    "RN_IND", ["M-WRK-PRD"]),
    RoomNameConcept("RN_IND_MNT", "RN-IND-MNT", "Maintenance Bay", "Wartungsbucht",
                    "Bay for equipment maintenance.", "Bucht fuer Geraetewartung.",
                    "RN_IND", ["M-WRK-PRD"]),
    RoomNameConcept("RN_IND_CLN", "RN-IND-CLN", "Clean Room", "Reinraum",
                    "Controlled-environment production room.", "Produktionsraum mit kontrollierter Umgebung.",
                    "RN_IND", ["M-WRK-PRD"]),
    RoomNameConcept("RN_IND_YRD", "RN-IND-YRD", "Covered Yard", "Ueberdachter Hof",
                    "Covered exterior work or storage yard modeled as space.", "Ueberdachter Aussenarbeits- oder Lagerhof als Raum modelliert.",
                    "RN_IND", ["M-WRK-PRD"]),
    # Technical (12)
    RoomNameConcept("RN_TEC_ELC", "RN-TEC-ELC", "Electrical Room", "Elektroraum",
                    "Room for electrical distribution equipment.", "Raum fuer elektrische Verteilung.",
                    "RN_TEC", ["S-TEC"]),
    RoomNameConcept("RN_TEC_HVC", "RN-TEC-HVC", "HVAC Plant Room", "HLK-Zentralraum",
                    "Room for heating, ventilation, and cooling plant.", "Raum fuer Heizungs-, Lueftungs- und Klimaanlagen.",
                    "RN_TEC", ["S-TEC"]),
    RoomNameConcept("RN_TEC_SRV", "RN-TEC-SRV", "Server Room", "Serverraum",
                    "Room for IT and network equipment.", "Raum fuer IT- und Netzwerktechnik.",
                    "RN_TEC", ["S-TEC"]),
    RoomNameConcept("RN_TEC_SPR", "RN-TEC-SPR", "Sprinkler Room", "Sprinklerraum",
                    "Room for fire suppression equipment.", "Raum fuer Sprinkler- und Loeschanlagen.",
                    "RN_TEC", ["S-TEC"]),
    RoomNameConcept("RN_TEC_PMP", "RN-TEC-PMP", "Pump Room", "Pumpenraum",
                    "Room for pumps and fluid handling.", "Raum fuer Pumpen und Fluessigkeitstechnik.",
                    "RN_TEC", ["S-TEC"]),
    RoomNameConcept("RN_TEC_BOI", "RN-TEC-BOI", "Boiler Room", "Heizungsraum",
                    "Room for boilers and heat generation.", "Raum fuer Heizkessel und Waermeerzeugung.",
                    "RN_TEC", ["S-TEC"]),
    RoomNameConcept("RN_TEC_CHL", "RN-TEC-CHL", "Chiller Room", "Kaelteraum",
                    "Room for chillers and cooling plant.", "Raum fuer Kaelteanlagen.",
                    "RN_TEC", ["S-TEC"]),
    RoomNameConcept("RN_TEC_GEN", "RN-TEC-GEN", "Generator Room", "Generatorraum",
                    "Room for backup power generation.", "Raum fuer Notstromaggregate.",
                    "RN_TEC", ["S-TEC"]),
    RoomNameConcept("RN_TEC_MMR", "RN-TEC-MMR", "Meter Room", "Zaehlerraum",
                    "Room for utility metering equipment.", "Raum fuer Verbrauchszaehler.",
                    "RN_TEC", ["S-TEC"]),
    RoomNameConcept("RN_TEC_TRA", "RN-TEC-TRA", "Transformer Room", "Transformatorenraum",
                    "Room for electrical transformers.", "Raum fuer Transformatoren.",
                    "RN_TEC", ["S-TEC"]),
    RoomNameConcept("RN_TEC_WST", "RN-TEC-WST", "Waste Room", "Abfallraum",
                    "Room for waste collection and handling.", "Raum fuer Abfallsammlung.",
                    "RN_TEC", ["S-TEC"]),
    RoomNameConcept("RN_TEC_COM", "RN-TEC-COM", "Communications Room", "Kommunikationsraum",
                    "Room for telecom and low-voltage systems.", "Raum fuer Telekommunikations- und Schwachstromanlagen.",
                    "RN_TEC", ["S-TEC"]),
    # Storage (8)
    RoomNameConcept("RN_STO_GEN", "RN-STO-GEN", "General Storage", "Allgemeiner Lagerraum",
                    "Room for general material storage.", "Raum fuer allgemeine Materiallagerung.",
                    "RN_STO", ["S-STO-GEN"]),
    RoomNameConcept("RN_STO_ARC", "RN-STO-ARC", "Archive Room", "Archivraum",
                    "Room for document and record archives.", "Raum fuer Dokumenten- und Aktenarchive.",
                    "RN_STO", ["S-STO-GEN"]),
    RoomNameConcept("RN_STO_JAN", "RN-STO-JAN", "Janitor Closet", "Hauswarteschrank",
                    "Small room for cleaning supplies and equipment.", "Kleiner Raum fuer Reinigungsmaterial.",
                    "RN_STO", ["S-STO-GEN"]),
    RoomNameConcept("RN_STO_MAL", "RN-STO-MAL", "Mail Room", "Postraum",
                    "Room for incoming and outgoing mail.", "Raum fuer Postein- und -ausgang.",
                    "RN_STO", ["S-STO-GEN"]),
    RoomNameConcept("RN_STO_SUP", "RN-STO-SUP", "Supply Room", "Materialraum",
                    "Room for consumable supplies.", "Raum fuer Verbrauchsmaterial.",
                    "RN_STO", ["S-STO-GEN"]),
    RoomNameConcept("RN_STO_COL", "RN-STO-COL", "Cold Storage", "Kuehlraum",
                    "Refrigerated storage room.", "Gekuehlter Lagerraum.",
                    "RN_STO", ["S-STO-GEN"]),
    RoomNameConcept("RN_STO_EQP", "RN-STO-EQP", "Equipment Storage", "Geraetelager",
                    "Storage for tools and equipment.", "Lager fuer Geraete und Werkzeuge.",
                    "RN_STO", ["S-STO-GEN"]),
    RoomNameConcept("RN_STO_ULD", "RN-STO-ULD", "Unloading Storage", "Annahmelager",
                    "Temporary storage at delivery point.", "Zwischenlager am Annahmeort.",
                    "RN_STO", ["S-STO-GEN"]),
    # Outdoor (8)
    RoomNameConcept("RN_OUT_BLN", "RN-OUT-BLN", "Balcony", "Balkon",
                    "Exterior projecting platform accessed from inside.", "Vom Innern erschlossene Aussenplattform.",
                    "RN_OUT", ["O"]),
    RoomNameConcept("RN_OUT_TRR", "RN-OUT-TRR", "Terrace", "Terrasse",
                    "Exterior paved or decked platform.", "Aussenliegende Terrassenflaeche.",
                    "RN_OUT", ["O"]),
    RoomNameConcept("RN_OUT_PAT", "RN-OUT-PAT", "Patio", "Innenhof",
                    "Enclosed or semi-enclosed outdoor sitting area.", "Innenhof oder Patio.",
                    "RN_OUT", ["O-GRN-REC"]),
    RoomNameConcept("RN_OUT_CWK", "RN-OUT-CWK", "Covered Walkway", "Ueberdachter Gang",
                    "Covered exterior pedestrian route.", "Ueberdachter Aussenweg.",
                    "RN_OUT", ["O-CIR-PED"]),
    RoomNameConcept("RN_OUT_GDN", "RN-OUT-GDN", "Garden Area", "Gartenflaeche",
                    "Landscaped outdoor area as space.", "Als Raum modellierte Gartenflaeche.",
                    "RN_OUT", ["O-GRN-GDN"]),
    RoomNameConcept("RN_OUT_PLY", "RN-OUT-PLY", "Playground", "Spielplatz",
                    "Outdoor play area.", "Aussenliegender Spielbereich.",
                    "RN_OUT", ["O-GRN-REC"]),
    RoomNameConcept("RN_OUT_SPL", "RN-OUT-SPL", "Pool Area", "Beckenflaeche",
                    "Outdoor pool or water feature area.", "Aussenliegende Becken- oder Wasserflaeche.",
                    "RN_OUT", ["O-GRN-REC"]),
    RoomNameConcept("RN_OUT_PRT", "RN-OUT-PRT", "Portico", "Portikus",
                    "Covered exterior entrance structure.", "Ueberdachter Aussenanbau am Eingang.",
                    "RN_OUT", ["O-CIR-PED"]),
    # Void (8)
    RoomNameConcept("RN_VOI_SHA", "RN-VOI-SHA", "Shaft", "Schacht",
                    "Vertical service or circulation shaft.", "Vertikaler Technik- oder Erschliessungsschacht.",
                    "RN_VOI", ["S-VOI-VRT"]),
    RoomNameConcept("RN_VOI_PLN", "RN-VOI-PLN", "Plenum", "Installationszwischenraum",
                    "Ceiling or floor service void.", "Installationshohlraum in Decke oder Boden.",
                    "RN_VOI", ["S-VOI-PLN"]),
    RoomNameConcept("RN_VOI_ATR", "RN-VOI-ATR", "Atrium Void", "Atrium",
                    "Multistory open interior volume.", "Mehrgeschossiger offener Innenraum.",
                    "RN_VOI", ["S-VOI-MLT"]),
    RoomNameConcept("RN_VOI_STR", "RN-VOI-STR", "Structural Void", "Konstruktionshohlraum",
                    "Void within structural elements.", "Hohlraum in tragenden Bauteilen.",
                    "RN_VOI", ["S-VOI-STR"]),
    RoomNameConcept("RN_VOI_PRK", "RN-VOI-PRK", "Interior Parking Stall", "Innenparkierplatz",
                    "Individual parking space within a structure.", "Einzelner Parkierplatz in geschlossener Anlage.",
                    "RN_VOI", ["S-PRK-INT"]),
    RoomNameConcept("RN_VOI_MCH", "RN-VOI-MCH", "Mechanical Void", "Technikhohlraum",
                    "Non-accessible mechanical void.", "Nicht begehbarer Technikhohlraum.",
                    "RN_VOI", ["S-VOI-PLN"]),
    RoomNameConcept("RN_VOI_RIS", "RN-VOI-RIS", "Riser", "Steigzone",
                    "Vertical building services riser.", "Vertikale Gebaeudetechnik-Steigzone.",
                    "RN_VOI", ["S-VOI-VRT"]),
    RoomNameConcept("RN_VOI_AIR", "RN-VOI-AIR", "Air Space", "Luftraum",
                    "Non-occupiable air volume in the model.", "Nicht nutzbarer Luftraum im Modell.",
                    "RN_VOI", ["S-VOI"]),
]


def activity_local_name(code: str) -> str:
    return code.replace("-", "_")


def enum_key_from_notation(notation: str) -> str:
    return notation.lower().replace("-", "_")


def ttl_escape(value: str) -> str:
    return value.replace("\\", "\\\\").replace('"', '\\"')
