classDiagram
  direction TB
  Entity <|-- ScheduleDependency
  Entity <|-- ScheduleItem
  ScheduleItem <|-- Milestone
  Entity <|-- ScheduleTemplate
  Entity <|-- VirtualEntity
  VirtualEntity <|-- AbstractCostRecord
  AbstractCostRecord <|-- CostAssembly
  AbstractCostRecord <|-- CostItem
  VirtualEntity <|-- ConnectionVirtual
  VirtualEntity <|-- Material
  VirtualEntity <|-- Space
  VirtualEntity <|-- SpatialContext
  SpatialContext <|-- BuiltAssetContext
  BuiltAssetContext <|-- BuildingContext
  BuiltAssetContext <|-- CivilStructureContext
  SpatialContext <|-- LegalSiteContext
  SpatialContext <|-- LevelContext
  SpatialContext <|-- PerimeterContext
  SpatialContext <|-- ProjectContext
  SpatialContext <|-- ZoneContext
  VirtualEntity <|-- System
